### ISSUE TITLE
Add support for COUNTKEYSINSLOT. 

### ISSUE THREAD

**Issue by christophstrobl** [mp911de/lettuce#107]
Would be great to have `clusterCountKeysInSlot(int slot)` in `RedisClusterConnection`.

**Comment by mp911de** [comment]
Will provide the method in 3.3 and 4.0

**Comment by mp911de** [comment]
Done for 3.3, needs merge to 4.0

**Comment by mp911de** [comment]
3.3-SNAPSHOT available on Sonatype's OSS Repo (https://oss.sonatype.org/content/repositories/snapshots)

**Comment by mp911de** [comment]
Implemented.
