### ISSUE TITLE
[4.0-beta1] Enable timeout when using Async API

### ISSUE THREAD

**Issue by vptheron** [mp911de/lettuce#115]
I'm using the Async API to query Redis.  I want a behavior where, when Redis is down, the client tries to reconnect periodically and while the connection is down it fails the commands immediately.

I tried setting a timeout on the client and the connection, hoping that the connection would send a timeout that would fail the future with a TimeoutException, however, what I see is all the commands being added to an internal queue to be later executed as soon as Redis is back up.

How can I configure my client/connection to make sure my Future complete with a failure after a specific amount of time when the connection is down?  I want to avoid growing a queue of backedup commands.

**Comment by mp911de** [comment]
Hi @vptheron, 
lettuce (3.x and 4.x) allows currently all-or-nothing: Either you get transparent reconnects with internal queueing of commands or no reconnects at all but then with canceling commands when the connection is disconnected. 

Please be aware that canceling commands do not reduce the internal queue size. As soon as Redis available again and the connection is restored, canceled commands will not be triggered to the Redis instance. 

You can use for now the not-so-obvious extensibility support of lettuce to implement the desired behavior on top of lettuce. By using this approach, you need to implement two classes on top of lettuce:

1. Extending the `RedisClient` (or `RedisClusterClient`, depending on which client you use)
2. Extending the `StatefulRedisConnectionImpl` (or `StatefulRedisPubSubConnectionImpl`, `StatefulRedisSentinelConnectionImpl`, depending on which connection type you use)

You can use the protected methods to extend lettuce and as soon as lettuce 4.0.Final is released the API will remain stable, breaking changes will be avoided under all circumstances.

I published a demo and a JUnit test how the code could look like. You can find the code in the following Gist: https://gist.github.com/mp911de/407632a6b98e6ee36180

HTH, Mark

**Comment by vptheron** [comment]
Thanks a lot for the fast response and the gist, that's what I had in mind since I was fearing your answer about "all-or-nothing" :)

> Please be aware that canceling commands do not reduce the internal queue size. As soon as Redis available again and the connection is restored, canceled commands will not be triggered to the Redis instance.

That's interesting.  So even if the commands are canceled and won't be played once the connection is re-established, they are enqueued.  Is there a way to avoid that?  I'm worried about the unbounded queue growing indefinitely while the client tries to reconnect.

**Comment by mp911de** [comment]
No, there is no way to aviod that behavior. However, I could think of adding a command/queue limit as a [Client option](https://github.com/mp911de/lettuce/wiki/Client-options) since limiting the queue can help to keep your application alive.

**Comment by mp911de** [comment]
@vptheron ping. Just wanted to check whether the limitation-by-abstraction way is suitable for you? PR's are also welcome.

**Comment by vptheron** [comment]
@mp911de I ended up implementing a custom timeout at the `Future` level.  Not ideal but I really had to use the async API while guaranteeing a specific timeout for the caller.

I think it would be great to make the size of the internal queue configurable, or even disable the "retry-on-reconnect" behavior altogether.

I may end up trying to add what I was missing when I find the time :)

Appreciate your help very much, thanks.

**Comment by mp911de** [comment]
Appreciate your feedback. I'll keep this one open for implementing the queue limit.

**Comment by mp911de** [comment]
Implemented `requestQueueSize` for lettuce 3.4 and 4.0.

**Comment by mp911de** [comment]
About the retry-on-reconnect behavior: The retry-on-reconnect mechanism has some implications on the behavior, meaning that switching it off is a fallback to at-most-once message delivery. Another question is: What happens with commands issued while the connection is in a disconnected state? I do not have enough information to decide on these topics yet.

**Comment by mp911de** [comment]
Implemented `requestQueueSize` within the context of this ticket, will track the disconnected-behavior in #121
