### ISSUE TITLE
Improve Codec API

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#118]
The Codec API is based on `RedisCodec` which defines methods to encode and decode keys and values. The class has following issues:

* asymmetric methods: `encode` returns `byte[]` whereas `decode` accepts `ByteBuffer`
* The class is abstract, but could be easily an interface (raised by @prepor)
* Users have to create a `byte[]`. This is not explicitly necessary. All encoded values are written into a nio `ByteBuffer`, so only a source for bytes is needed (raised by @beckje01)

Constraints of the improved API:

* Break as little as possible and preserve RedisCodec as much as possible
* Change the `connect()` methods in a compatible way

Proposed change:
1. ~~Introduce a new abstraction of `RedisCodec` that returns `ByteBuffer` on `encode`~~ Another abstraction requires to change all API's where `RedisCodec` is referenced. Plan B: Turn `RedisCodec` into an interface
2. Adopt existing codecs
3. Explain migration in the 3.x to 4.x migration guide

Why `ByteBuffer`? `ByteBuffer`s are handles to memory and encapsulate data. Netty's `ByteBuf`s work internally with `ByteBuffer`s and can produce references to the data without actually duplicating it. `ByteBuffer` is used already in `RedisCodec`.

**Comment by mp911de** [comment]
After implementing the code, I'm not sure whether it's worth the change.

**Comment by beckje01** [comment]
I think it looks good and eliminates the byte duplication that was required with the byte[] at the codec stage. Also all for switching it to an interface, looks nice and clean.

**Comment by mp911de** [comment]
Implemented for 4.0
