### ISSUE TITLE
"ERR invalid password" when creating a RedisURI with a username

### ISSUE THREAD

**Issue by jsiebens** [mp911de/lettuce#131]
When deploying an application to Heroku with the Heroku Redis addon, a Redis URI with a username is provided. Eg: redis://h:<password>@<...>.compute-1.amazonaws.com:14589
This results in an "ERR invalid password" error because the username is not correctly stripped from the password.

**Comment by mp911de** [comment]
Please not that Redis authentication is based only on passwords. Passing passwords within URL's is supported but it misses somehow the point since the URI UserInfo syntax is `USER:PASSWORD`. Passwords with special chars such as `:` and `@` cannot be used because they conflict to the URI syntax.

**Comment by mp911de** [comment]
Fixed in 3.4 and 4.0

**Comment by mp911de** [comment]
Fixed also in 3.3
