### ISSUE TITLE
RedisHashAsyncCommands hmget should return Map, not List

### ISSUE THREAD

**Issue by longkerdandy** [mp911de/lettuce#132]
I'm using 4.0Beta2
The hmget return RedisFuture<List<V>>, better to be RedisFuture<Map<K, V>>

**Comment by mp911de** [comment]
Thanks for the feedback. The reason for the current design is the redis response structure:

```
127.0.0.1:6379> hmset key f1 v1 f2 v2
OK
127.0.0.1:6379> hgetall key
1) "f1"
2) "v1"
3) "f2"
4) "v2"
127.0.0.1:6379> hmget key f1 f2
1) "v1"
2) "v2"
```

`HMGET` does not return the keys within the answer and currently this is the only way (except streaming) to retrieve hash values in the order they were inserted. All `Map` results use a `HashMap` to transport the data.

What is your motivation for the change request?

**Comment by longkerdandy** [comment]
If redis is designed that way, I can deal with the result myself, thanks.

**Comment by mp911de** [comment]
Thanks for your fast response. So nothing to do here.
