### ISSUE TITLE
Use LinkedHashMap instead of HashMap for Map outputs

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#133]
The response maps use the `HashMap` implementation to transport map data structures. A `HashMap` has a random order and does not preserve the Redis ordering. Switch therefore to a `LinkedHashMap`.

Motivation: A LinkedHashMap preserves the order of elements whereas a HashMap maintains a "random order". The order of Redis hash values depends on the order of insertion. Users might want to preserve that order and that's the reason why to use a LinkedHashMap.

References:
* http://stackoverflow.com/questions/26414757/linkedhashmap-behaviour-with-redis-hashes
* http://stackoverflow.com/questions/31767537/jedis-hmset-map-insertion-order

**Comment by mp911de** [comment]
You can observe the ordering aspect when inserting a small number of elements. Order is also retained across restarts (persistence). I am not familiar with conditions under which the insertion order is being changed, however it is a neat effect worth being preserved.

**Comment by prdoyle** [comment]
Very true! I only wish it were a stronger guarantee, like in MongoDB.
