### ISSUE TITLE
GEOADD passes long/lat parameters in the wrong order to Redis

### ISSUE THREAD

**Issue by IdanFridman** [mp911de/lettuce#134]
Redis GEOADD API expecting latitude,longitude (with that order)

Lettuce API has the opposite order:
RedisFuture<Long> geoadd(K key, double longitude, double latitude, V member);

Thanks,
Idan.

**Comment by mp911de** [comment]
Affected versions: 3.3, 3.4 and 4.0

**Comment by mp911de** [comment]
It's actually the other way round. Redis expects `longitude latitude` (see http://redis.io/commands/geoadd). The API has the correct signature, but the values are passed in the wrong order towards Redis. The parameter order was switched during the Geo API development (see https://github.com/antirez/redis/issues/2705). In contrast to the current impl, Matt's implementation used `latitude longitude`.

**Comment by mp911de** [comment]
Fixed 4.0-SNAPSHOT available on https://oss.sonatype.org/content/repositories/snapshots/

**Comment by IdanFridman** [comment]
Thank you.

2015-09-10 8:46 GMT+03:00 Mark Paluch <notifications@github.com>:
