### ISSUE TITLE
Cluster pub/sub and resilient subscriptions

### ISSUE THREAD

**Issue by jpennell** [mp911de/lettuce#138]
I'm using the Lettuce client in a project that uses pub/sub. For reliability reasons, my service also connects to a Redis cluster to take advantage of master/slave failover in failure scenarios.  

Lettuce is able to handle master/slave failover for commands like get/set/etc. however, I don't see a way for Lettuce to recover pub/sub subscriptions in failure scenarios. 

Since `subscribe()` and `unsubscribe()` are only available from the pub/sub interface returned by `RedisClient.connectPubSub()`, if that node goes down, the cluster will continue to operate but I'll lose all my subscriptions.

An ideal scenario would be something like the following: 

# Getting a cluster pub/sub connection

**Async**

```java
final RedisClusterClient clusterClient = new RedisClusterClient(uri);
final RedisClusterPubSubAsyncCommands<String, String> asyncClusterPubsub = clusterClient.connectPubSub().async();
```

**Reactive**

```java
final RedisClusterClient clusterClient = new RedisClusterClient(uri);
final RedisClusterPubSubReactiveCommands<String, String> reactiveClusterPubsub = clusterClient.connectPubSub().reactive();
```

# Subscribing

**Async**

```java
asyncClusterPubsub.addListener(new RedisPubSubListener<String, String>() {
    ...
});
asyncClusterPubsub.subscribe(channelId).whenComplete((success, error) -> {
     ...
});
```

**Reactive** 

```java
reactiveClusterPubsub.observeChannels().subscribe(message -> {
    ...
});
reactiveClusterPubsub.subscribe(channelId).subscribe(success -> {
    ...
});
```

When a consumer subscribes to a channel using cluster pub/sub Lettuce would:

1. Subscribe to the channel on a node in the cluster.
    * This node can be a master node, or a slave node, both function identically for pub/sub
    * Subscriptions should be well distributed amongst all nodes in the cluster. Maybe issuing new subscribe commands to nodes that currently have the least subscriptions.
1. Lettuce stores information about which node a subscription is associated with
1. Whenever a message arrives from any subscription, regardless of origin Redis node,Lettuce distributes that message to consumers using the existing `RedisPubSubListener` or channel observable.

From the consumers perspective, pub/sub against a cluster or a single Redis node looks essentially identical. Under the hood though, the clustered implementation distributes subscriptions to multiple Redis nodes.

# Unsubscribing

**Async**

```java
asyncClusterPubsub.unsubscribe(channelId).whenComplete((success, error) -> {
     ...
});
```

**Reactive** 

```java
reactiveClusterPubsub.unsubscribe(channelId).subscribe(success -> {
    ...
});
```

When a consumer unsubscribes from a channel using cluster pub/sub Lettuce would:

1. Look up which node the subscription is associated with
1. Unsubscribe from the channel on that specific node in the cluster
1. Remove the association of this channel from Lettuce's internal subscription map

# Publishing

Currently the publish command is available on the existing `RedisAdvancedClusterAsyncCommands` interface.  In it's existing implementation, Lettuce distributes publish commands only to master nodes (though it does distribute them to multiple master nodes).  Since publish commands can be sent to any node in the cluster, including slaves, the implementation of this command should distribute publish commands randomly to all nodes rather than just master nodes.

# Topology changes

When new nodes are added to the cluster, existing topology refreshes will pick up the new node.  

Lettuce should:

1. Create a new pub/sub connection to that node
1. Store node id -> pub/sub connection so it can be used for pub/sub commands
1. Distribute subscribe requests to this node using a distribution method mentioned above

# Node Failure

This is the most important reason for this effort. If a node in a Redis cluster goes down Lettuce should:

1. Detect the node going down (already done though topology changes and connection events)
1. Clean up the pub/sub connection to that node
1. Clean up the list of subscriptions that were associated with that node
1. Re-issue subscribe commands from that node to other healthy nodes in the cluster

In this way subscriptions become resilient in a clustered environment.  Even if a node goes down, Lettuce will be able to detect this failure, and re-establish the consumers' subscriptions on other healthy nodes in the cluster.

**Comment by mp911de** [comment]
+1

Cluster pub/sub is totally decoupled from the key space and does not require key-based routing. I'm curious about the API and its relation to Standalone pub/sub. 

`RedisClusterClient` has already _some_ behavior for topology changes and reconnects. It takes always the first node from the `Partitions` for reconnect. Not sure, whether this is good or not, but it can be improved.

**Comment by mp911de** [comment]
Subscriptions should be well distributed amongst all nodes in the cluster. The client will track the number of connected clients and connect to the node with the least number of connected clients.

**Comment by mp911de** [comment]
The internal handling of pub/sub patterns and channel names routes the commands consistently to the master node that would serve the slot-hash based on the channel name

**Comment by mp911de** [comment]
Implemented.
