### ISSUE TITLE
Consider using Single<T> rather than Observable<T> for commands that return a single value

### ISSUE THREAD

**Issue by jpennell** [mp911de/lettuce#139]
Reactive extensions documents a `Single<T>` type, very similar to `Observable<T>` as follows: 

From http://reactivex.io/documentation/single.html 

> RxJava (and its derivatives like RxGroovy & RxScala) has developed an Observable variant called “Single.”
> A Single is something like an Observable, but instead of emitting a series of values — anywhere from none at all to an infinite number — it always either emits one value or an error notification.

For Redis commands that only return a single value, rather than a list of values, a `Single<T>` return type could be considered.

# Example

##### Existing interface for Redis `get` command with `Observable<T>`

```java
Observable<V> get(K key);
```

```java
redisConnection.get(key)
    .doOnError(error -> { ... })
    .doOnCompleted(() -> { ... })
    .subscribe(value -> { ... });
```

but as the documentation states, `Observable<T>` infers that an observable will emit

> anywhere from none at all to an infinite number [of values]

##### Proposed interface for Redis `get` command with `Single<T>`

```java
Single<V> get(K key);
```

```java
redisConnection.get(key)
    .subscribe(value -> { ... }, error -> { ... });
```

The benefit of the `Single<T>` type for single valued returns is that the consumer knows explicitly that there is a single value returned from this command, and you will always get either a value or an error.

**Comment by mp911de** [comment]
Thanks for the hint. `Single<T>` is annotated with `@Experimental` and it is not `instanceof Observable`. Need to get some thoughts about that.

**Comment by vleushin** [comment]
I'm not sure either. Single has almost the same API and you can chain it the same way. But it still has @Beta on it

**Comment by mp911de** [comment]
@vleushin since Ben left netflix the reactive library cards got shuffled again. There's very little movement towards rx-java 2 and Project Reactor looks most promising to me. Project Reactor uses `Mono` and `Flux` (lite, `Publisher` rich API) to indicate singular/0..N results. I'm not fully convinced yet to switch libraries but Project Reactor might become an option in future development.

**Comment by mp911de** [comment]
Closing this ticket as it's superseded by #214 the future of rx-java (rx-java 2).
