### ISSUE TITLE
Can't connect to redistogo service since 4.0

### ISSUE THREAD

**Issue by wowselim** [mp911de/lettuce#147]
I was able to connect to redistogo using the now deprecated classes. This changed when I updated to 4.0.Final.
As I have no access to a pc right now I'll link to my tweet with a screenshot here: https://twitter.com/seloflash/status/654974617170374656?s=09

**Comment by mp911de** [comment]
The code from your snippet looks OK.

I verified Redis access using the following snippet:

```java
RedisClient redisClient = RedisClient
        .create("redis://PW@bluegill.redistogo.com:9646/0");

RedisCommands<String, String> connection = redisClient.connect().sync();
System.out.println(connection.ping());

connection.close();
redisClient.shutdown();
```

Can you post more details, perhaps a stack trace?

**Comment by wowselim** [comment]
I am getting no more errors. I couldn't reproduce the bug myself eventhough I couldn't fix it earlier today. It doesn't occur on my other computer either. I guess it was an issue related to the network I was using earlier this day.
