### ISSUE TITLE
How to use lettuce with redis master/slaves replication

### ISSUE THREAD

**Issue by longkerdandy** [mp911de/lettuce#148]
From the document, I see lettuce works with Standalone Sentinel & Cluster. But I don't know how to use it with simple [replication setup](http://http://redis.io/topics/replication).

I asked this because some IaaS cloud provide redis service still limited to 2.8 master/slaves replication.

**Comment by mp911de** [comment]
Hi,
The use of a master/slave setup is as straightforward as Redis standalone.
Lettuce utilizes masters and slaves in a static configuration (i.e. no
failover detection/read from preference). You specify the master in your
RedisURI and connect as is was a Redis Standalone machine. My plan is to do
something about that with #125 but it's not my highest priority.

HTH, Mark

LongkerDandy <notifications@github.com> schrieb am Mi., 21. Okt. 2015 um
14:12:

**Comment by longkerdandy** [comment]
OK, understood

**Comment by mp911de** [comment]
Can I close this ticket?

**Comment by longkerdandy** [comment]
sure
