### ISSUE TITLE
How can I use lettuce with guice?

### ISSUE THREAD

**Issue by flyzb618** [mp911de/lettuce#149]
Now lettuce support cdi and spring ,but not guice.
     who can help me?

**Comment by mp911de** [comment]
Hi @flyzb618 
there are various styles how to integrate Lettuce with Google Guice. I upload an example to https://gist.github.com/mp911de/95b0879101da4ae4c229

HTH, Mark

**Comment by mp911de** [comment]
Question answered, closing therefore this ticket.
