### ISSUE TITLE
Implement distributed locks

### ISSUE THREAD

**Issue by longkerdandy** [mp911de/lettuce#150]
Redis provide a algorithm called Redlock, it is little complicated, better lettuce can implement it.
Or I have to use another redis client to handle the lock.
From offical site: http://redis.io/topics/distlock

**Comment by mp911de** [comment]
Hi @longkerdandy,
thanks for your feature-request. lettuce is a low-level client that allows users to execute Redis commands. High-level functionality such as distributed locks or object mapping are not in the scope of lettuce. However there are other clients like https://github.com/spring-projects/spring-data-redis and https://github.com/mrniko/redisson that provide high-level functionality for your application. It's worth taking a look on these libraries.

lettuce is intended to provide command-level access to Redis and to do its job in the best way possible.

**Comment by mp911de** [comment]
Closing.
