### ISSUE TITLE
Missing method to create an react command pool in RedisClient

### ISSUE THREAD

**Issue by dawnbreaks** [mp911de/lettuce#157]
Hi,
  It seems that there are not methods to create react command pool in RedisClient just like pool() and asyncPool for sync/async commands.

Thanks & Best Regards!

**Comment by mp911de** [comment]
The missing pool functionality for the reactive API is by purpose. Lettuce users usually do not require pooling at all since the connections are thread-safe. Adding connection pooling to lettuce was my biggest mistake.
