### ISSUE TITLE
rx set operation w/ SetArgs returns value itself instead of a String

### ISSUE THREAD

**Issue by joshdurbin** [mp911de/lettuce#159]
With a custom codec defined, 'set' operations (and possibly other operations) with SetArgs return an Observable of a specified type (matching the codec). The emitted item from this operation is essentially a String, which represents the redis server response for the operation, eg: "OK". Given that the method signature states it returns an object of the specified type (again, matching the codec), the codec's `decodeValue` method is executed with the input "OK" (or other response, if there's an error).

Unless the codec is written to decode this response in additional to actual, expected responses, it will bomb.

In testing, an unmodified codec (unmodified to handle the response, but working otherwise), the method signature below works:

`Observable<String> set(K key, V value)` 

...while this method signature fails w/ a codec exception of an unhanded "OK":

`Observable<V> set(K key, V value, SetArgs setArgs)`

**Comment by mp911de** [comment]
Thank you for reporting the bug. The method return type is required to change from `V` to `String` to fix the bug.

This bug affects 3.x and 4.x version. It will be fixed with 3.3.2.Final, 4.0.2.Final and the bugfix will be included in the future 3.4 and 4.1 versions.

**Comment by mp911de** [comment]
Fixed.

**Comment by mp911de** [comment]
Released 3.3.2.Final and 4.0.2.Final to Maven central.
