### ISSUE TITLE
How to disable formatting while adding long primitve

### ISSUE THREAD

**Issue by IdanFridman** [mp911de/lettuce#161]
I am doing the following code in lettuce:
  RedisClient client;
    RedisAsyncCommands<String, String> asyncCommands; 

asyncCommands.zadd(reqUserId, System.currentTimeMillis(), "{\"a:\")");
     

//System.currentTimeMillis()=1450110314264

if you monitor on Redis you get that:

1450109792.349288 [0 127.0.0.1:64872] "ZADD" "history:171" "1.450109792341E12" "{\"a:\")"

look at System.currentTimeMillis(). it formatted it into "1.450109792341E12"

When I tried to store is as plain String:

 RedisFuture<Long> futureResult = asyncCommands.zadd(reqUserId, "1450110314264", "{\"a:\")");

I get exception:
java.lang.String cannot be cast to java.lang.Double
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double

Any idea?
Thanks.

**Comment by mp911de** [comment]
Hi @IdanFridman 

that's just a formatting issue of the `MONITOR` command. The score must be numeric and not a string. I reproduced your code and got the following result:

```
127.0.0.1:6479> monitor
1450125025.857462 [0 127.0.0.1:64626] "ZADD" "key" "1.450125025851E12" "member"
1450125025.865902 [0 127.0.0.1:64626] "ZRANGE" "key" "0" "-1" "WITHSCORES"

...

127.0.0.1:6479> zrange key  0 -1 WITHSCORES
1) "member"
2) "1450125025851"
```

If you retrieve the entries from the sorted set (e.g. with `zrangeWithScores`) you'll see the numeric value is the one you put into the sorted set entry.

**Comment by IdanFridman** [comment]
You were right. my bad! thank you.
