### ISSUE TITLE
How do I use connection for multi thread?

### ISSUE THREAD

**Issue by uryyyyyyy** [mp911de/lettuce#180]
Hi.
I want to use `RedisClusterClient` with multi thread client with `StatefulRedisClusterConnection`.
but I cannot found how I should use connection.

in thins issue(https://github.com/mp911de/lettuce/issues/157), mp911de said we no need to use connection pool.

if so, which we should use for multi thread client access?
- reuse stateful connection
- every time we create new connection

Thanks!

**Comment by mp911de** [comment]
Hi @uryyyyyyy,

lettuce is thread-safe, you can reuse stateful connections across multiple threads. The only exception is if you use blocking commands such as `BLPOP`. When using blocking commands, you should use multiple connection to not block other threads.

お役に立ったなら幸いです, Mark

**Comment by uryyyyyyy** [comment]
@mp911de 
that's all I want to know!

Thanks!! I will use lettuce for our service.
