### ISSUE TITLE
Sending custom command

### ISSUE THREAD

**Issue by WhiteTrashLord** [mp911de/lettuce#182]
Please add this information on all Readmes:

lettuce 3.x works with Java 6, 7 and 8, lettuce 4.x requires Java 8

I tried version 4 with Java 7 :)

Is there an easy way how to send a custom command to the Redis server?

I need something like the Low level Redis client of redisson.

**Comment by mp911de** [comment]
Hi @WhiteTrashLord, 
I'll add the Java versions to the readme.

I'm not sure I understand your requirement. Lettuce is a low-level driver that allows to send Redis commands to Redis (`HMGET`, 'BLPOP', ...). Checkout the Javadocs at http://redis.paluch.biz/docs/api/releases/latest/com/lambdaworks/redis/RedisConnection.html

If these commands are not sufficient, you still can send commands by building your own command with args and an output-parser: https://github.com/mp911de/lettuce/wiki/Custom-commands%2C-outputs-and-command-mechanics

HTH, Mark

**Comment by WhiteTrashLord** [comment]
Sorry I have no idea why I didn't see that.

**Comment by mp911de** [comment]
Np, questions are always welcome.
