### ISSUE TITLE
RedisReactiveCommands#mget has wrong return type (4.0.2.Final)

### ISSUE THREAD

**Issue by HaloFour** [mp911de/lettuce#185]
The return type for `RedisReactiveCommands#mget` is `Observable<V>`, however the actual result is `Observable<List<V>>` (which is also mentioned in the Javadocs).

While it probably makes sense for the command to return `Observable<V>` and have each of the results emitted in the sequence this is not currently what it does which is causing me to forcibly cast to `Observable<List<V>>` in order to work with it correctly.

**Comment by mp911de** [comment]
Hi @HaloFour, 
thanks for the ticket. It comes actually to the best time because I'm about to release 4.1 soon (today?). Can you post some code? I tried to reproduce the problem but wasn't able to do so. The Javadoc is wrong, every collection type (Sets, Lists, but not Maps) are (should be) splitted into single elements.

**Comment by HaloFour** [comment]
@mp911de Ack, I think that you're right.  That's the second time that I've been bitten by my own bad mocks.  Converting from the async API to the reactive API and I had changed the mock from `RedisFuture<List<Object>>` to `Observable<List<Object>>`.  In any case the javadocs are wrong, so that's still an issue,  :smile:

As for the reactive results from `mget`, would the observable sequence contain `null` for keys that were not found, or would those be skipped?  I didn't see a mention of that specific behavior in the Wiki.

**Comment by mp911de** [comment]
Thanks for your feedback. It contains nulls, same as the List variant of mget. Otherwise, the sequence would get screwed up.

**Comment by mp911de** [comment]
Fixed.
