### ISSUE TITLE
Adapt, redirect or suppress logging about reconnecting

### ISSUE THREAD

**Issue by Gerard-at-Streamit** [mp911de/lettuce#193]
Hi,

Every now and then I get the message that connection was lost and restored:

152342 [pool-1-thread-1] INFO com.lambdaworks.redis.protocol.ConnectionWatchdog - Reconnecting, last destination was gar.redistogo.com/23.23.209.139:10105
152498 [pool-1-thread-1] INFO com.lambdaworks.redis.protocol.ConnectionWatchdog - Reconnected to gar.redistogo.com/23.23.209.139:10105

Under certain circumstances I want to change the format, redirect (to different log file) or suppress the message. I tried Log4J and found no way to achieve this. None of the following worked:

In log4j.properties (tried one at a time):
log4j.logger.com.lambdaworks.redis.protocol.ConnectionWatchdog=FATAL
log4j.category.com.lambdaworks.redis.protocol.ConnectionWatchdog=warn, stdout
log4j.logger.io.netty=FATAL
log4j.logger.com.lambdaworks.*=FATAL
log4j.rootLogger=OFF, stdout # Enable logging for specific other classes

In the Java code (tried one at a time):
Logger.getLogger("io.netty").setLevel(Level.OFF);
Logger.getLogger("com.lambdaworks.redis.protocol.ConnectionWatchdog").setLevel(Level.OFF);

Created a logback.xml, log4j.xml; alas, no joy.

Nor was there a setting in this package that enabled me to change logging settings.

Please advise!

Kind regards, Gerard

**Comment by mp911de** [comment]
Gerard, 

thanks for your ticket. Lettuce uses netty's logger resolution to find the available logger infrastructure. The order is:

1. Use slf4j if possible
2. Use log4j if possible
3. Fallback to java.util.logging if slf4j/log4j not available.

You need to check your log frameworks that are on the class-path.

The class, you're interested in muting is `com.lambdaworks.redis.protocol.ConnectionWatchdog`, setting the log-level to `WARN` or `ERROR` might help you to reduce the noise. An increased number of reconnects is a hint that either the network is unstable or that Redis drops inactive connections (can be configured).

I attached a `log4j.properties` that works for this case:

```
log4j.rootLogger=INFO, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

log4j.logger.com.lambdaworks.redis.protocol.ConnectionWatchdog=ERROR
```

Please come back to me if that doesn't help.

**Comment by Gerard-at-Streamit** [comment]
Hi Mark,

 

Thank you for the superfast and comprehensive feedback. I use Log4J () and replaced the log4j.properties with the contents you proposed. However, this seems to be ignored by the particular class:

 

2016-02-11 21:33:18 INFO  RedisListener:98 - Subscribed to customer1

2016-02-11 21:33:19 INFO  RedisListener:64 - customer1={"password":"i-d1949862","appName":"live","ipAddress":"52.90.201.151","username":"wowza"}

152309 [pool-1-thread-1] INFO com.lambdaworks.redis.protocol.ConnectionWatchdog - Reconnecting, last destination was gar.redistogo.com/23.23.209.139:10105

152453 [pool-1-thread-1] INFO com.lambdaworks.redis.protocol.ConnectionWatchdog - Reconnected to gar.redistogo.com/23.23.209.139:10105

 

As the logging shows, the config is read (the first lines are formatted as per the instructions you sent and I copied). The last two lines have a different formatting…

 

Any help would be much appreciated.

 

PS: Given that the reconnects are irregular even if nothing happens, seems to suggest to me that the server does not disconnect on idle. Otherwise the idle connectino would be broken at regular intervals it would seem. 

 

Kind regards,

Gerard

 


Streamit BV

Langendijk 7, 5652 AX Eindhoven, Nederland

KvK: 17192664

 


Email:  <mailto:gerard@streamit.eu> gerard@streamit.eu

Tel.nr: 040 2556036

Web:  <http://www.streamit.eu/> www.streamit.eu

Skype: gerardhollemans

**Comment by mp911de** [comment]
It looks like you have anything else on your class-path. I assume it is `slf4j-simple`. If you check the docs of the `slf4j-simple` logger, you'll notice the formats are similar: http://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html

You could replace `slf4j-simple` by the appropriate `slf4j-log4j12` module (see http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.slf4j%22%20AND%20a%3A%22slf4j-log4j12%22)

**Comment by Gerard-at-Streamit** [comment]
Hi Mark,

 

You’re right, slf4j-simple (1.6.1) is in the POM… You are not only fast, but also sharp. Thank you. I will check this out tomorrow.

 

Kind regards,

Gerard

 


Streamit BV

Langendijk 7, 5652 AX Eindhoven, Nederland

KvK: 17192664

 


Email:  <mailto:gerard@streamit.eu> gerard@streamit.eu

Tel.nr: 040 2556036

Web:  <http://www.streamit.eu/> www.streamit.eu

Skype: gerardhollemans

**Comment by Gerard-at-Streamit** [comment]
Hi,

Switched to slf4j-log4j12, works like a breeze. Your help is much appreciated.

Kind regards,
Gerard
