### ISSUE TITLE
when using with tomcat, it will block tomcat's stoping

### ISSUE THREAD

**Issue by abc549825** [mp911de/lettuce#200]
Version: 4.0.2.Final
`com.lambdaworks.redis.AbstractRedisClient` has a field called "timer"(instance of HashedWheelTimer) which  would created a executor. However, the executor has  not be shutdown gracefully, so it would casuse tomcat block when trying to stop the tomcat process(bootstrap). 

So i have to do someting tricky when shutdown the tomcat in my web app:
```java
        try {
            Field field = AbstractRedisClient.class.getDeclaredField("timer");
            field.setAccessible(true);
            ((HashedWheelTimer) field.get(client)).stop();
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }
```
plz correct me if i am wrong.

**Comment by abc549825** [comment]
I found it.

**Comment by mp911de** [comment]
The timer is stopped in any case if the `shutdown(...)` method is called. See https://github.com/mp911de/lettuce/blob/4.0.1.Final/src/main/java/com/lambdaworks/redis/AbstractRedisClient.java#L238
