### ISSUE TITLE
The future of the lettuce reactive API

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#214]
lettuce brought with 4.0 a reactive API based on rx-java 1. The reactive API mirrors mostly the asynchronous API and resolves `List` and `Set` types into `Observable`. The reactive API has some drawbacks:

* It emits `null` values
* Method invocation and result processing are decoupled. In some cases, data ordering depends on the input arguments that can make it hard to correlate input parameters to result
* (more to come)?

Reactive libraries move towards [Reactive Streams](http://reactive-streams.org), and the rx-java 1 library will be superseded by rx-java 2 that will use Reactive Streams as well.

Especially the `null` handling is in Reactive Streams pretty clear defined: `null` values are not allowed which means lettuce has to react to this requirement. 

## The `null` problem

Redis emits `null` in several cases. The most frequent case might be `MGET` to retrieve values by a key. In case the key does not exist, a `null` value is returned. Returning `null` values is discouraged anyways, with Reactive Streams it's no longer allowed. This rule requires lettuce to introduce a representation for absent values. While it's simple for singular values like `GET` to use a `Mono` (see [Project Reactor](http://projectreactor.io), multiple absent values are harmful to the API consumer because it cannot be longer correlated, which value of e.g. a `MGET` is absent. 
It's obvious for at least commands returning multiple values by key to return a different result type than the value type. Something like `Publisher<Value<T>>` could wrap the value.

## The ordering problem

Result order in the sync/async API is not an issue. The result type of commands using a particular order is either `List` or a `Map` using a `LinkedHashMap` implementation. The input argument order can be easily matched against the result ordering since both values are quite near to each other. Reactive APIs introduce the possibility for deferred and lazy event processing where the stream can be processed in a different place than the command invocation. Emitting just the value type might be not enough in that case.

A possible solution might introduce a keyed value type that holds the correlation to the input argument. Currently `GET` and `MGET` and its variants are known to fall into this category of commands.
Something like `Publisher<KeyValue<K, V>>` could wrap the value.

**Comment by vleushin** [comment]
Regarding ```null``` problem -- what about ```Optional```? Also, as far as I know -- lettuce do not return ```null``` in Reactive API? I use ```lastOrDefault(null)``` to get around this.

I also had ordering problem, but a bit in different context. I ended up with simillar wrapper, or, if object returned from Redis had this key inside -- without wrapper.

**Comment by mp911de** [comment]
Thank you for your feedback. You're right, `GET` does not return a `null` but `MGET` does. I fixed the description.

Try `reactive.mget("a", "b", "c").doOnNext(s -> System.out.println(s)).doOnCompleted(() -> System.out.println("complete")).subscribe();` where the keys are absent. It prints: 

```
null
null
null
complete
```

**Comment by longkerdandy** [comment]
If Reactive Streams it's no longer allowed null value, bypass it by using wrapper class doesn't seem to be a good idea. IMHO, if lettuce return with the correlation of the key and value, it seems null value could just be skipped.

**Comment by jedwardsaviata** [comment]
Rather than using position to pair resulting values with requested fields, why not supply a collection containing key/value pair objects for those values which were non-null? If the alternative is using `Optional`, there isn't much added overhead, and the source of each value is more explicit.

**Comment by mp911de** [comment]
@jedwardsaviata I thought about something like `KeyValue<K, V>` which would transport the key and the value, like an `Optional` with a key.

**Comment by mp911de** [comment]
Following methods are known to emit arrays containing null-elements at top-level:

* `mget(K...)`, could emit `KeyValue<K, V>`
* `hmget(K,K...)`, could emit `KeyValue<K, V>`
* `geohash(K, V...)`, could emit `Optional<String>`
* `sort(…)`, could emit `KeyValue<K, V>`
* `bitfield(…)`, could emit `Optional<Long>`
* `exec(…)`, could emit `Optional<Object>`

**Comment by mp911de** [comment]
RxJava announced its roadmap towards 2.0. RxJava will feature a couple of breaking changes. It will be compliant with Reactive Streams but requires each `Observable` and `Single` to be converted to a `Flowable`. The other way round, `Observable`/`Single` creation is possible with `Observable.from(Publisher)`.

I've worked with Reactive Streams and RxJava and I have to admit the Project Reactor implementation provides a very clean an concise API. I'm tempted to drop RxJava in favor of Project Reactor. Supporting both libraries is not doable by myself. RxJava users can convert `Publisher <-> Observable` in both directions using the provided Project Reactor adapters.

Any opinions?

**Comment by vleushin** [comment]
I see your point. Being able to convert is big plus.Have you worked with Project Reactor elsewhere?

**Comment by mp911de** [comment]
I'm currently building reactive APIs for MongoDB and Cassandra using Project Reactor. Working with RxJava/Project Reactor reveals small differences and the Project Reactor API feels more mature. RxJava 1 has a different internal architecture which prevents some optimizations that are made by Reactor. The devs of RxJava contribute to Reactor and vice versa so you find similar code in both projects.

**Comment by mp911de** [comment]
I've migrated the reactive API for lettuce `5.0.0` to use project reactor and Reactive Streams. You can take a first look on the very first snapshot builds:

```xml
<dependency>
    <groupId>biz.paluch.redis</groupId>
    <artifactId>lettuce</artifactId>
    <version>5.0.0-SNAPSHOT</version>
</dependency>
```

**Comment by mp911de** [comment]
Closing this ticket as the direction is clear now. The reactive API was migrated to Reactive Streams/Project Reactor with #349.

**Comment by mp911de** [comment]
Users of RxJava 1 can benefit from the upcoming command interfaces abstraction (dynamic API) by declaring RxJava1/RxJava2 return types. Wrapper type conversion happens under the hood and the migration path improves by retaining RxJava on a different abstraction level, see #383.
