### ISSUE TITLE
Reduce Google Guava usage

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#217]
Guava is a commonly used library that can cause dependency conflicts. Reduce the usage of Google Guava in lettuce 4.2 so lettuce can hopefully get rid of it one day:

* `Lists` and `Maps` and immutable collections/maps
* Cache and Cache Builder
* `AbstractInvocationHandler`
* `Preconditions`

**Comment by barmic** [comment]
Why do you want avoid  immutable collections/maps ?

**Comment by mp911de** [comment]
I'm not avoiding immutable collections/maps but I version conflicts because of Guava. Guava is used nearly everywhere and here and there in a driver or common framework (Cassandra Driver, Vaadin, Jackson, and 11526 other public artifacts according to [VersionEye](https://www.versioneye.com/java/com.google.guava:guava/references)). Some API's are changing/removed within Guava so upgrading to a higher version carries always the risk of breaking things. I'm also not fan of relocating (shading) 2MB of Guava for "just" a bunch of helpers.

**Comment by barmic** [comment]
Ok I understand.
You will implement your own immutables collections ?

Thank you for your answer :)

**Comment by mp911de** [comment]
No need for own immutable collections since Java provides `Collections.unmodifiableList` et. al.

**Comment by mp911de** [comment]
Implemented. The remaining parts use `LoadingCache` and `HostAndPort` on the public API.
