### ISSUE TITLE
Gracefully shutdown DefaultCommandLatencyCollector.PAUSE_DETECTOR

### ISSUE THREAD

**Issue by sf-git** [mp911de/lettuce#223]
Lettuce 4.1.1.Final

DefaultCommandLatencyCollector.PAUSE_DETECTOR is a SimplePauseDetector. And SimplePauseDetector starts threads in its constructor that need to be shutdown gracefully.

**Comment by mp911de** [comment]
Good catch, I'll take a look.

**Comment by johnou** [comment]
At least it shouldn't block shutdown because they are daemon threads?

**Comment by mp911de** [comment]
This ticket introduces some complexity as `DefaultCommandLatencyCollector.PAUSE_DETECTOR` is held in a static instance. Pause detector threads (4 threads) are started when `DefaultCommandLatencyCollector` is initialized statically. It's not required to have multiple instances of `SimplePauseDetector` but it's required to stop the threads once they aren't needed anymore. 
 
So the resulting changes would be:

1. Initialize `SimplePauseDetector` as late as possible (maybe even through an `AtomicReference`) on the first usage
2. Register a VM shutdown hook to stop `SimplePauseDetector`

**Comment by mp911de** [comment]
Thanks for the support and the bug report, fixed.
