### ISSUE TITLE
Contributing link doesn't work or exist

### ISSUE THREAD

**Issue by SebastienBenazet** [mp911de/lettuce#226]
Contributing link doesn't work properly :
https://github.com/mp911de/lettuce/blob/master/.github/CONTRIBUTING.md

**Comment by mp911de** [comment]
Please help me understand what does not work as expected?

**Comment by SebastienBenazet** [comment]
It returns a 404 error when i try to reach it from the README

https://github.com/mp911de/lettuce/pull/227

**Comment by mp911de** [comment]
Thanks a lot, that's merged with 4c68f60bf5fdab1968710fa4a9f3ca0aa881ad98.
