### ISSUE TITLE
4.2 commandBuffer flush slow

### ISSUE THREAD

**Issue by CodingFabian** [mp911de/lettuce#228]
hi Mark,
i am trying latest snapshot.
The `com.lambdaworks.redis.protocol.CommandHandler.flushCommands()`impl is slow
<img width="613" alt="bildschirmfoto 2016-04-22 um 11 53 04" src="https://cloud.githubusercontent.com/assets/176132/14738638/1c3de066-0883-11e6-908e-7f627eb76f5e.png">

My guess that the copy and remove pattern is inefficient.
Unfortunately the implementation does not have a drainTo Method, so I propose to do the following

```
                    queuedCommands = new ArrayList<>(commandBuffer.size());
                    RedisCommand<K, V, ?> cmd;
                    while ((cmd = commandBuffer.poll()) != null) {
                      queuedCommands.add(cmd);
                    }
```

this requires command buffer to be `Deque`

```
  public final static <T> Deque<T> newConcurrentDeque() {
    return PlatformDependent.newConcurrentDeque();
  }
```

sounds good for you? then i can make a pr. otherwise I am looking forward to a better solution :)

**Comment by mp911de** [comment]
Thanks for your research. Have you profiled your proposal using `poll()`? I'm currently removing Guava from the code so there is a lot of refactoring going on (see https://github.com/mp911de/lettuce/blob/issue/217/src/main/java/com/lambdaworks/redis/internal/LettuceFactories.java). Code looks good but I'd propose to wait couple of days until I complete my work on the branch and then feel free to create a PR.

**Comment by CodingFabian** [comment]
I will do so next, but the profiles are hard to compare right now the flush method is the most expensive in a 10 minute profile, so thats why i had a look.
i assume my proposal is faster because it is doing a single pass over the collection rather than two (including equals checks)

**Comment by CodingFabian** [comment]
I can confirm my change is better. hard to get reliable numbers. happy to provide y patch once your work is done, or you directly incorporate it.

**Comment by mp911de** [comment]
Thanks a lot. Let me finish the Guava refactoring, then I'll apply your code.

**Comment by mp911de** [comment]
Implemented.
