### ISSUE TITLE
RedisClient.connect(RedisURI) fails for unix socket based URIs

### ISSUE THREAD

**Issue by nivekastoreth** [mp911de/lettuce#229]
**Observed Version**: 4.1.FINAL
* See [RedisClient.java Line 788](https://github.com/mp911de/lettuce/blob/4.1.Final/src/main/java/com/lambdaworks/redis/RedisClient.java#L788)

**Still visible in Master**: Yes
* See [RedisClient.java Line 789](https://github.com/mp911de/lettuce/blob/master/src/main/java/com/lambdaworks/redis/RedisClient.java#L789)

**Expected**:
All `connect` implementations properly handle unix-socket based URIs

**Actual**:
The following code fails due to an assertion that is invalid for unix-socket connections:
```
RedisClient.create().connect(RedisURI.create("redis-socket:///redis/redis.sock"))
```
The invalid assertion, quoted below, asserts that host is not empty which is always false for unix-socket URIs
```
private void checkValidRedisURI(RedisURI redisURI) {
    checkArgument(redisURI != null && isNotEmpty(redisURI.getHost()), "A valid RedisURI with a host is needed");
}
```

**Workaround:**
Using the `codec, uri` connect method instead bypasses this invalid assertion
```
RedisClient.create().connect(new Utf8StringCodec(), RedisURI.create("redis-socket:///redis/redis.sock"))
```

**Note**:
The fact that the workaround works is itself most likely a bug

**Comment by mp911de** [comment]
Thanks for this amazing bug report.

**Comment by mp911de** [comment]
Fixed for all versions (3.x, 3.4.x, master [4.x] and 4.1.x).
