### ISSUE TITLE
The shaded version of lettuce breaks EPollProvider

### ISSUE THREAD

**Issue by taer** [mp911de/lettuce#230]
Pretty minor issue with EPollProvider
`epollEventLoopGroupClass = getClass("io.netty.channel.epoll.EpollEventLoopGroup");`

When maven shades this line, it appends com.lambdaworks to the front. The problem is, the epoll library is not included(perfectly fine, it's optional). So the class in the classpath is  
`io.netty.channel.epoll.EpollEventLoopGroup`
while the EPollProvider is looking for 
`com.lambdaworks.io.netty.channel.epoll.EpollEventLoopGroup`

I tried to add a filter for 
`io.netty.channel.epoll.*
io.netty.channel.unix.*`

to the maven shade relocate. It didn't change much. The string the code was looking for became
`com/lambdaworks/io.netty.channel.epoll.EpollEventLoopGroup`

The workaround is to simply not use the shaded version of lettuce. Not sure how to make shade-plugin do the right thing.

**Comment by mp911de** [comment]
Thanks for the bug report. I think the bugfix is quite simple as the code needs to check both class names (`io.netty.…` and `com.lambdaworks.io.netty.…`).

**Comment by taer** [comment]
I think the shade plugin is altering that string. The source I have for Epoll doesn't reference com.lambdaworks at all, but the arg to getClass leads with it.

**Comment by mp911de** [comment]
My bad. I just started reproducing the issue, then I recognized the optional package is not shaded at all.

**Comment by mp911de** [comment]
The fix is to remove the `com.lambdaworks` prefix in `getClass`. I'll include the fix for 3.4.2, 3.4.x, 4.1.2 and 4.x. The only other option seems to be writing an own Shader.
