### ISSUE TITLE
Add support for OpenSSL implementation in netty

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#249]
Add support for the OpenSSL implementation in as an alternative to the JDK SSL implementation. OpenSSL yields better performance and creates less garbage.

**Comment by mp911de** [comment]
Implemented.

**Comment by Geek2Sages** [comment]
I want 2 ask U how 2 use the pipeline for fast add/query 100million keys as fast as possible...
How 2 use the pipeline? In what class's what method ?
Or I have better way to solve the problem ?
---------------------------------------------------------------------
My aim is 2 implements a Redis-Java api for query Trillion keys as fast and high-concurrency as possible, so batch-query is needed...Which method can used 4 batch-query?(one query no longer than 50ms)
And what is the advantage of using Lettuce?
---------------------------------------------------------------------
I am sorry for trouble U...I am a chinese so my English is poor...And it is very hard in China to search some technical info...Can U tell me where 2 ask programming questions and which website has more about redis in java?
Thank U very much!

**Comment by mp911de** [comment]
@Geek2Sages I created a new ticket #279 to continue the discussion as your comment is not related to SSL support.
