### ISSUE TITLE
RedisClusterClient default connection congestion

### ISSUE THREAD

**Issue by pcchan** [mp911de/lettuce#252]
Following up from my [question](https://groups.google.com/forum/#!topic/lettuce-redis-client-users/mUO8fAxS4wQ) in the Google Group.

As mentioned in the documentation, connections created with `RedisClusterClient` will always create a default connection to the node with the lowest latency. However, this may cause congestion when one node has a lower latency. If all clients experience the lowest latency with a particular node, then all clients will pick that node for its default connection. 

In my case I'd be happy to use randomly selected nodes. That gives me a more predictable distribution of connections. Perhaps some environments prefer selecting by latency, but maybe lettuce could expose the choice as a client configuration?

**Comment by mp911de** [comment]
Thanks for the ticket. The default connection is created to the first node able to connect. `RedisClusterClient` starts to its connection attempts with the first entry of the `Partitions` collection (ordered by latency). Randomly selected nodes will work, but it's not a deterministic approach.

There are two other options which both seem reasonable to me:

1. Sticking to the order of seed nodes: The connection attempts are performed in the order the seed nodes are provided. This approach gives full control to the user.
2. Using the client count: Lettuce obtains the client connection count for each cluster node while topology discovery (can be disabled) and `Partitions` is ordered by the client count. Obtaining the number of client connections beyond the seed nodes can be disabled with the upcoming 4.2 version which is useful when running large clusters.

**Comment by mp911de** [comment]
The default will be to connect to the node with the least clients. For now `RedisClusterClient` will expose `getSocketAddressSupplier(Function<Partitions, Collection<RedisClusterNode>> sortFunction)` which can be overriden to specify an own function. lettuce ships with `TopologyComparators` that expose predefined sorting methods (`sortByUri`, `sortByClientCount` and `predefinedSort`). Applying a sorting function requires to subclass `RedisClusterClient` for now as this is the least invasive approach.

`predefinedSort` allows to use the initial seed nodes as predefined ordering and apply it to the dynamic topology results from `Partitions`. Nodes that are not found in the initial seed nodes are ordered by the URI (lexicographical comparison of the host and port string, i.e. `127.0.0.1:6379` < `127.0.0.1:6380`). The block of nodes not found in the predefined order comes after the block of nodes with a predefined order.

**Comment by mp911de** [comment]
Implemented.
