### ISSUE TITLE
How to handle unavailable Redis transparently

### ISSUE THREAD

**Issue by namero999** [mp911de/lettuce#254]
This issue is actually just a question, please tag as such.

Thanks for the work on Lettuce, I appreciate the craftsmanship behind this code.

I have been experimenting with a few Java Redis drivers and I decided to go with either Lettuce or Jedis. For as much as I would like to use Lettuce, there's one use case that I was able to solve immediately with Jedis while I struggled with Lettuce, most likely because I failed at figuring it out. Hence this question:

how to handle unavailable Redis instances at startup, and how to transparently reconnect?

Basically, I would like the creation of RedisClient to always succeed at startup, and deal with errors only when needed (mostly at command execution time).

I use the following code.

```java
RedisClient redisClient = RedisClient.create("redis://password@localhost:6379/0");
StatefulRedisConnection<String, String> connection = redisClient.connect();
RedisCommands<String, String> syncCommands = connection.sync();

syncCommands.set("key", "Hello, Redis!");
```

But at startup time, this code explodes at `connect()` if no Redis is available. Jedis uses connection pools, so the pool itself is always created, and I can deal with errors only when I try to speak with Redis (set command).

A few considerations. Jedis' pool approach is nice because connection attempts are made when I need it, and I get an exception only when I try to use it. On the other hand, I completely agree with your comment (sorry, I just remember reading it but I can't find the source now) about pools being mostly useless in common scenario, where most likely, if a connection is down, all of them are down. Having a thread-safe connection is the way to go, but I would like the usage of it to be transparent, auto-fixing and gracefully degradable.

In short, I would like to get to the point where I can use RedisCommands without worrying about my Redis availability, and having a mechanism that automatically tries to reconnect, so that eventually my commands will work.

Is there anyway to achieve this with Lettuce?

(extra datapoint: I currently deal with a single Redis instance, not a cluster)

A nice model in my mind is the following.

* A RedisClient always succeed, and has a connection.
* The connection can have a state, established or not.
* A non-established connection makes commands fail-fast (so, not trying to connect synchronously).
* A non-estrablished connection spawns a background task that periodically tries to reconnect.
* An established connection executes commands successfully.
* If those commands fail with a network error, the commands throw exceptions and reconnection attempts are spawned again.

**Comment by mp911de** [comment]
Thanks for your ticket. lettuce connections provide auto-reconnection and thread-safety out of the box. You can [disable auto-reconnect](https://github.com/mp911de/lettuce/wiki/Client-options#auto-reconnect) and you can configure the [connection behavior for disconnected connections](https://github.com/mp911de/lettuce/wiki/Client-options#disconnected-behavior).

Lettuce provides also a pool which imposes the delayed connection behavior. If the Redis server is not available at startup time, then you won't see any exceptions unless you allocate a connection.

lettuce allows several options to be configured on a connection using [`ClientOptions`](https://github.com/mp911de/lettuce/wiki/Client-options) so let me take your list and add my answers to these:

* A RedisClient always succeed, and has a connection: Works only with connection pooling ❗ 
* The connection can have a state, established or not: That's already the case ✅ 
* A non-established connection makes commands fail-fast (so, not trying to connect synchronously). Configurable ✅ 
* A non-established connection spawns a background task that periodically tries to reconnect. Configurable, enabled by default ✅ 
* An established connection executes commands successfully. That's already the case ✅ 
* If those commands fail with a network error, the commands throw exceptions and reconnection attempts are spawned again. Configurable, enabled by default ✅

**Comment by namero999** [comment]
Thanks a lot. I will take a second look at the links you provided.

I forgot to mention in my previous message that I'm aware about the pooling mechanism in Lettuce, but I've read that it is considered deprecated (although the code is not annotated as such). What should we expect in the future about this feature? Anyway, I would like not to use pooling.

Can you then confirm that I got your reply correctly? The initial connect() MUST succeed. If it succeed, then the reconnect mechanism is in place, and I'm safe to use commands knowing that I will get an exception as long as the connection has not been re-established by some sort of background task. The initial unavailability must be instead handled manually by my code. Is this the correct way of doing thing with Lettuce?

**Comment by mp911de** [comment]
Confirming that you got me right. 

As long as there's no replacement for some aspects connection pooling solves (transactions, blocking operations), I can't deprecate pooling. Having a feature you should not use but there's not replacement won't help anyone.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by namero999** [comment]
Hi Mark, I believe this ticket can be closed being just a question. I'm evaluating again the usage of Lettuce. Thanks.

**Comment by mors741** [comment]
Hello Mark!

Thanks for Lettuce, I am big fan!

I would like to have this behavior in Lettuce too.
Currently we have to implement this kind of reconnections on our side.

### That’s why I believe it should be a driver feature
Suppose that connection established successfully,
then it failed,
and then reestablished again.

In this scenario I have `StatefulRedisConnection` all the time and reconnection are executed transparently for my code. It's cool!

But
if connection failed at init, I get exception and I have to retry it myself.

Important point here is that my server can live without Redis. So, I don't want to kill server, if Redis down - I want to retry connection later.

### My suggest is
1. Introduce a Client Option like `allowInitConnectionFail`.
2. If `true` and connection can't be established at init, then just left it in closed state (`isOpen()=false`).
3. Reconnect later on user commands as usual.

I really don't want to bring Connection Pooling only to handle unavailability on startup 😕 

If you are OK with general concept, I can try to implement it myself.

**Comment by mp911de** [comment]
@mors741 That could be an interesting extension for Lettuce to allow deferred connection initialization. Feel free to have a look. We have various places (Redis standalone, Redis Sentinel, Cluster, Master/Replica) where we would need to implement that feature. Care to file a ticket before submitting a PR?
