### ISSUE TITLE
Null value has been discard

### ISSUE THREAD

**Issue by dawnbreaks** [mp911de/lettuce#261]
Hi, in the reactive commands api, null value will be discarded. I think this behavior is not acceptable. The following code not work as expected,  the get command will return null but actually null is discard and not pass to the next observable.
```java

ReactiveRedisClient.reactiveCommands()
          .get("account:" + userId)
          .flatMap(accountName -> {
              System.out.println("accountName=" + accountName);
              if (accountName == null) {
                  return ReactiveRedisClient.reactiveCommands().get("null:uuid");
              } else {
                  return ReactiveRedisClient.reactiveCommands().get(accountName + ":uuid");
              }
          }).map(uuid -> {
              System.out.println("uuid=" + uuid);
              if (uuid == null) {
                  return "uuid is null";
              } else {
                  return uuid;
              }
          });
```

**Comment by dawnbreaks** [comment]
Hi, i hope that someone will fix it soon. @mp911de  Are you free to fix it recently? I think this bug is a little critical.

**Comment by mp911de** [comment]
Feel free to submit a pull request but the issue needs to be investigated first for the true cause. `null` handling is always sort of special and reactive frameworks according to reactivestreams.org prohibit `null` values and their mapping/processing.

**Comment by dawnbreaks** [comment]
I think that all nullable result T should return with Optional<T> instead of returning T directly. It seems that need to do a big change on API.

**Comment by mp911de** [comment]
I created #214 a while ago to explain the transition and the outlook for the reactive API.

**Comment by mp911de** [comment]
The main issue here is the API has no consistent behavior. Let's take a look at the following examples:

The first example

```java
reactive.get("unknown")
        .doOnNext(s -> System.out.println("Single element: " + s))
        .doOnCompleted(() -> System.out.println("Single element complete"))
        .toBlocking()
        .singleOrDefault("");
```
 just prints

```
Single element complete
```
it does not emit any items but completes. It's clear from the result that the absent value correlates with the requested key. It follows the suggested rx-java pattern of an empty `Observable` and corrects from a Reactive Streams perspective.

The second example:

```java
reactive.mget("unknown1", "unknown2", "unknown3")
        .doOnNext(s -> System.out.println("Multiple elements: " + s))
        .doOnCompleted(() -> System.out.println("Multiple elements complete"))
        .toBlocking()
        .single();
```

prints 

```
Multiple elements: null
Multiple elements: null
Multiple elements: null
Multiple elements complete
```

It works using rx-java but wrong from a Reactive Streams perspective. Skipping `null` values in a response which emits multiple values causes confusion about the key the response belongs to.

At this point, wrapper types need to kick in. That will be part of a larger change towards Reactive Streams with lettuce 5. Emitting elements for singular `null` values would break existing code so not going to change this behavior.

**Comment by mp911de** [comment]
Closing this ticket for now as it works as designed. The issue will be revisited in lettuce 5.
