### ISSUE TITLE
Replacement support for connection pooling

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#264]
lettuce connection pooling is a deprecated feature, but there is a demand to provide pooling in certain cases.
The long-term idea is to remove all pooling-related methods (`pool(…)`, `asyncPool(…)`) from `RedisClient` to step back regarding visibility.

A replacement could look like leaving a `RedisConnectionPool` class. It would implement common pooling code (such as `PooledObjectFactory`, returning objects by implementing an auto-closeable proxy) but leave all other configuration options to the user. Users benefit from having a framework-provided pooling base but are free in creating and tweaking the pool.

A non-opinionated pooling support creates the base to use pooling on top of `RedisClient` and `RedisClusterClient` if it's truly required.

**Comment by HaloFour** [comment]
We're currently using `GenericObjectPool` directly to manage a pool of `RedisReactiveCommands<K, T>` so that commands are round-robin dispatched over the connections in the pool (non-LIFO).  The one thing that absolutely sucks about Apache's pool implementation being that it is blocking which negates a lot of the benefit of using the reactive interfaces.

**Comment by mp911de** [comment]
Why do you use pooling?

**Comment by HaloFour** [comment]
@mp911de

Primarily to distribute the commands over multiple connections as we were finding with a single shared connection that we would seem to saturate that connection during spikes in throughput.  We're using redis+lettuce for a shared cache and it's not uncommon to exceed 100k requests/min and we'd ideally like the response time under 50ms.  We're connecting to AWS Elasticache.

I don't know if we're a good example of when you'd want to use connection pooling.  I mostly reused `GenericObjectPool` as that's what lettuce previously used and I liked the easy configuration and in non-LIFO mode it effectively provided the round-robin strategy that I wanted.  My comment is more than when you're using an async library that it defeats the purpose to have an operation block when using that library.

**Comment by mp911de** [comment]
Have you benchmarked performance of a single connection vs. multiple connections? My benchmarks always yielded a higher throughput and less latency by using one connection. Pooling is OK in case you use blocking commands or transactions, besides that, it just eats up resources.

I'm not aversed of getting rid of `commons-pool2` in favor of something that suits better.

**Comment by HaloFour** [comment]
@mp911de Anecdotally I can say that the rate of Hystrix command timeouts decreased when we went with a pool of 16 connections but I don't have any numbers to back that up in any way.  We are using MULTI in some scenarios, specifically to work around Redis's lack of an MSET command with an expiration, but I don't think that was a very frequent operation.  We do keep the connection borrowed until EXEC completes in that case.

**Comment by mp911de** [comment]
That's interesting. I've never met someone who hit timeouts in regular operations (network troubles or long running scripts aside). If you stumble upon an issue to improve inside lettuce, let me know.

**Comment by mp911de** [comment]
Implemented.
