### ISSUE TITLE
RedisCommand#exists is deprecated. Needs alternative.

### ISSUE THREAD

**Issue by andradei** [mp911de/lettuce#265]
I need to check whether a Hash exists before getting data from it. What is the current functionality for Redis' `EXISTS`?

**Comment by mp911de** [comment]
`boolean exists(K key)` was replaced by `long exists(K... keys)`

**Comment by andradei** [comment]
Can I use `RedisKeyCommands` wherever I'd use `RedisCommands`?

**Comment by mp911de** [comment]
Use whatever suits you the best. `RedisKeyCommands` and all the other segregation interfaces expose subsets of commands which are combined into `RedisCommands` at the top level.
