### ISSUE TITLE
Add support for variadic LPUSHX and RPUSHX

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#267]

**Comment by mp911de** [comment]
Done.

**Comment by gneokleo** [comment]
According to the spec here: http://redis.io/commands/rpushx RPUSHX doesn't support varargs. Same for LPUSHX too. I also tested locally with the latest stable Redis 3.2.1 and I confirmed that varargs don't work with those commands. Am I missing something?

**Comment by mp911de** [comment]
Variadic `LPUSHX` and `RPUSHX` live until now only in the `unstable` branch of Redis (see https://github.com/antirez/redis/commit/ab73544396de1ba9ca7ef6b065517c9411a1a1bf). The command support isn't released with lettuce 4 yet.

**Comment by gneokleo** [comment]
Thanks! This makes more sense now
