### ISSUE TITLE
Redis URI timeout seems to be a maximum value and not a default value.

### ISSUE THREAD

**Issue by guperrot** [mp911de/lettuce#271]
Hi,

RedisURI has a "timeout for synchronous command execution".

But when using the async API, calling get with a timeout value greater than the redis URI timeout does not work, the redis URI timeout is used no matter what. 

Does that mean the redis URI timeout Javadoc is actually misleading and is rather a maximum timeout for any command whether the used API is sync or async?

Another issue I have is integrating lettuce with brpop: brpop has a timeout of its own at Redis protocol level, but actually when passing 0 for "wait forever", the java API throws a timeout exception after the redis uri configured timeout (which defaults to 1 minute). How can I avoid that redis URI timeout to take over?

**Comment by mp911de** [comment]
Hi @guperrot

The timeout on `RedisURI` applies only to synchronous commands. Currently, it works a bit confusing as the timeout is taken from the `RedisClient` instance which is set when creating a `RedisClient` using a `RedisURI`.

Connecting Redis using `RedisClient.connect(RedisURI)` will use the default timeout from the `RedisClient` and not the timeout from the used `RedisURI`.

The timeout applies only to synchronous calls. Asynchronous and reactive usage are not protected by the timeout. The timeout on synchronous calls is mainly to protect the application. An expired timeout does not cancel the command if it's already sent to the Redis server. Redis needs to respond first before other commands are executed on the same connection.

Commands accepting a timeout (as the blocking list commands) pass the timeout as an argument to Redis, but the timeout does not affect the synchronous command timeout. The only way avoiding the synchronous timeout taking over is using the asynchronous API and using `RedisFuture.get()` without arguments.

Please note that an active command (= not completed) is retriggered if the connection breaks. This means if you run a blocking command with an infinite timeout and the connection gets disconnected by the network/server then the command is re-sent to Redis which would again cause your client to wait.

**Comment by guperrot** [comment]
Ok thanks for the clarification.

However the redis uri timeout is actually applied to RedisClusterClient (I have not tested with non cluster).

```

**Comment by guperrot** [comment]
It is also applied to reconnection timeout by the way, this value of 5s was in `RedisURI`:

> 2016-06-15 18:34:39,437 | WARN  | lettuce-eventExecutorLoop-1-2 | ConnectionWatchdog | Cannot connect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 5 SECONDS

Which again is good in my scenario ;)

**Comment by mp911de** [comment]
Fyi: lettuce 4.3 will come with `SocketOptions` which separates the timeout for the TCP connect and initialization. That affects connection/reconnection in the sense as reconnection has a connect part (where the connection timeout is applied) and the initialization part (SSL, `AUTH`, `PING`) where the command timeout is applied.

The changes of #273 apply only to the non-cluster `RedisClient`.

In lettuce 4.2 and earlier the command timeout is applied to both, connection and initialization.

**Comment by guperrot** [comment]
Ok, thanks for the answers.
