### ISSUE TITLE
Fix JavaDoc for blocking list commands

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#272]
JavaDoc for blocking list commands is obviously wrong:

`RedisListCommands` says for `blpop`:

```
@param timeout the key
@param keys the timeout type: long
```

Same for `brpop` and `brpoplpush` on all list command interfaces.

**Comment by mp911de** [comment]
Done.

**Comment by asad-awadia** [comment]
@mp911de is it possible to get an unlimited timeout for blpop?
