### ISSUE TITLE
how 2 use the pipeline for fast add/query (original post by Geek2Sages)

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#279]
I want 2 ask U how 2 use the pipeline for fast add/query 100million keys as fast as possible...
How 2 use the pipeline? In what class's what method ?
Or I have better way to solve the problem ?
---------------------------------------------------------------------
My aim is 2 implements a Redis-Java api for query Trillion keys as fast and high-concurrency as possible, so batch-query is needed...Which method can used 4 batch-query?(one query no longer than 50ms)
And what is the advantage of using Lettuce?
---------------------------------------------------------------------
I am sorry for trouble U...I am a chinese so my English is poor...And it is very hard in China to search some technical info...Can U tell me where 2 ask programming questions and which website has more about redis in java?
Thank U very much!

Original post by @Geek2Sages https://github.com/mp911de/lettuce/issues/249#issuecomment-226665530

**Comment by mp911de** [comment]
Hi @Geek2Sages, 

no worries about your English. Mine isn't too good as well :)

From your questions I propose you should get familiar with Redis at all as Redis is blazing fast (100.000 to 1.000.000 operations/sec). Lettuce keeps up with the performance and provides a thread-safe, asynchronous connection.

The [lettuce wiki](https://github.com/mp911de/lettuce/wiki/) contains an article about [Pipelining](https://github.com/mp911de/lettuce/wiki/Pipelining-and-command-flushing) which explains the underlying concepts. You might want to get a basic understanding for performance mechanics first, so reading a book (http://www.brendangregg.com/sysperfbook.html) is always a good idea. Question-driven development isn't something that will lead you to a well-performing software.

In general, [StackOverflow](http://stackoverflow.com/) is a good place to ask questions once you've got a basic understanding of the topic.

Further references:
* https://github.com/mp911de/lettuce/wiki
* http://stackoverflow.com/questions/32857922/jedis-and-lettuce-async-abilities
* https://stackoverflow.com/questions/28023162/is-there-a-redis-library-which-handles-the-pipelining-automatically

**Comment by Geek2Sages** [comment]
And where can I find an example of using lettuce's transaction & pipeline ?
Examples of using lettuce is hard to find in Google...

**Comment by mp911de** [comment]
Guess there aren't much examples. Using batching/transactions requires a dedicated connection (per Thread) otherwise the other Threads can cause congestion or interfere with the batching/transactional state. lettuce does pipelining by default, the only thing you can do additionally is perform batching (collecting commands before writing those) but that requires the use of the async API:

```
StatefulRedisConnection<String, String> connection = client.connect();

connection.setAutoFlushCommands(false);

RedisAsyncCommands<String, String> commands = connection.async();
commands.multi();

// call multiple commands
commands.get/set/del/hmset/lpush(…);

RedisFuture<String> multi = commands.multi();

commands.setAutoFlushCommands(true);
commands.flushCommands();

multi.thenAccept(…)
```

The resulting futures are processed after the `MULTI` call completes and the commands are flushed (written) to the TCP connection. You can add listeners to the individual futures or to the multi future, depending on how you want to design the asynchronous flow.

**Comment by Geek2Sages** [comment]
# **Thank U very much !**

**Comment by mp911de** [comment]
Closing this issue as it seems solved.
