### ISSUE TITLE
Reactive lettuce usage

### ISSUE THREAD

**Issue by aakn** [mp911de/lettuce#281]
Hey,

We are facing an issue with Reactive Lettuce where on a high concurrency we are getting errors.
So just wanted to get a confirmation that we are using Lettuce correctly.

Lettuce Version: 4.1.2.Final

Usage: https://gist.github.com/aakn/376f525434db328bf703bb00c2819a0c

We are hitting the max client limit at redis (which is configured at 10,000)
Are we doing this right? Do we have tweak any configurations? Should we be closing the connections here?

**Comment by mp911de** [comment]
Thanks for your question. It's good to construct the client once but the code could be improved:

1. `connect()` on each `Observable` construction. That's a blocking call.
2. Connections aren't closed. You create with each call a new connection and the connection isn't ever closed.

```
  @Override
  protected Observable<String> construct() {

    String[] redisKeys = keys.stream()
        .toArray(String[]::new);

    RedisReactiveCommands<String, String> commands = client.connect().reactive();

    return commands.mget(redisKeys)
        .filter(Objects::nonNull);
  }
```

lettuce connections and APIs are thread-safe. Please reuse `StatefulRedisConnection` (`client.connect()`), a connection can be shared across multiple threads and that's a best practice. 

See also https://github.com/mp911de/lettuce/wiki/About-lettuce

**Comment by aakn** [comment]
Thanks for the quick reply.
To close on this, would you suggest reusing a single connection throughout the application? Or should I be creating a ConnectionPool?

**Comment by mp911de** [comment]
Using one single connection across the whole application is a very good idea. It requires the least resources and is most effective. Multiple connections/connection pooling is only required for transactions, blocking list commands or in some scripting scenarios.

**Comment by aakn** [comment]
Sounds good. Will try this out.
