### ISSUE TITLE
RedisAsyncCommands.pfadd(K,V...)/pfcount/pfmerge  & RedisCommands.pfadd(K,V...)/pfcount/pfmerge are ambiguous.

### ISSUE THREAD

**Issue by christophstrobl** [mp911de/lettuce#282]
`RedisHLLAsyncCommands.pfadd(K key, V... values)` &  `RedisHLLAsyncConnection.pfadd(K key, V value, V... moreValues)` combined in `RedisAsyncCommands` forces you to cast to one of the two.

It's basically the same for `pfcount` and `pfmerge` and the sync `RedisHLLCommands`.

**Comment by mp911de** [comment]
Thanks for the ticket. I currently see two solutions (happy to see more suggestions) to the issue:

1. The intermediate: Either use casting on argument level or use the API by accessing the commands through `RedisHLLCommands`/`RedisHLLAsyncCommands` typed instances
2. The long-term: I plan to remove the deprecated API `RedisConnection` and `RedisAsyncConnection` (also the segregated `Redis…Connection`/`Redis…AsyncConnection` interfaces) with lettuce 5.0 (see #156)

**Comment by mp911de** [comment]
That's fixed in 5.0 with aac999acc4c163eeacf1b67517df68c817b35e66.
