### ISSUE TITLE
Reusing EventLoopGroups

### ISSUE THREAD

**Issue by przemyslaw-elias** [mp911de/lettuce#283]
I've come across https://github.com/mp911de/lettuce/wiki/Configuring-Client-resources looking for a way of reusing already created Netty EventLoopGroups and not having other created.

I tried setting my worker eventLoopGroup as eventExecutorGroup on ClientResources, but I can still see that lettuce spawns it's own pool "lettuce-nioEventLoop".

How do I make lettuce use only my EventLoopGroup to prevent context switches?

Example code:
```
ClientResources clientResources = DefaultClientResources.builder()
                .eventExecutorGroup(workerEventLoopGroup)
                .build();
RedisURI redisUri = RedisURI.builder().withHost(redisHost).withPort(redisPort).build();
RedisClient redisClient = RedisClient.create(clientResources, redisUri);
RedisConnectionPool<RedisAsyncCommands<byte[], byte[]>> redisAsyncCommandsRedisConnectionPool = redisClient.asyncPool(new ByteArrayCodec(), redisClientPoolSize, redisClientPoolSize);
```

I'm using Lettuce 4.2.0.

**Comment by mp911de** [comment]
cześć!

lettuce uses two (or more) executor groups:

1. `EventExecutorGroup` for scheduling of tasks or `Future` listener notifications
2. One or two `EventLoopGroups` (NIO and EPoll have their own implementations)

You can supply your own `EventLoopGroup` implementing the `EventLoopGroupProvider` interface and supplying that instance in `ClientResources`. The default implementation uses reference counting to eagerly dispose `EventLoopGroup`s if they aren't needed, but that's just an optimization.

HTH, Mark

**Comment by przemyslaw-elias** [comment]
Cześć & thanks for quick answer! :)

Do I get it correctly that I'll have to implement bare `EventLoopGroupProvider` and not use `DefaultEventLoopGroupProvider` (since the latter can only create/allocate new EventLoopGroups which I don't want)?

**Comment by mp911de** [comment]
Yes, that would be the solution for now. I'm always eager for feedback and how to improve lettuce.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by przemyslaw-elias** [comment]
That's all I needed, thanks!
