### ISSUE TITLE
Reactive API and RxJava Internal Operator Classes

### ISSUE THREAD

**Issue by HaloFour** [mp911de/lettuce#284]
The class `RedisAdvancedClusterReactiveCommandsImpl` currently directly uses the internal RxJava class `OperatorConcat`.  This class was removed from RxJava in version 1.1.2 which is causing me problems as I have other dependencies which require that I update to a more recent release of RxJava.

RxJava exposes `Observable.concat` which already accepts an `Observable<Observable<T>>`, is there a reason Lettuce did not use this method?

**Comment by HaloFour** [comment]
I've submitted two PRs which switch `RedisAdvancedClusterReactiveCommandsImpl` from using the removed class to instead using the `Observable.concat` helper method:

https://github.com/mp911de/lettuce/pull/285
https://github.com/mp911de/lettuce/pull/286

**Comment by mp911de** [comment]
Thanks for your PRs. There was no particular reason for not using `concat(Observable<? extends Observable<? extends T>>)`. 

I merged both PR's and picked your changes also to `master`. I don't expect another `4.1.x` but I scheduled a `4.2.1` release for next week.
