### ISSUE TITLE
Guard value parameters against null values.

### ISSUE THREAD

**Issue by christophstrobl** [mp911de/lettuce#291]
Using `null` values on commands that do not expect `null` causes NPE on invocation. The error in `MessageToByteEncoder.write` is swallowed. This then causes a `RedisCommandTimeoutException`- instead of the actual error.

```java
connection.append("mp911de".getBytes(), null);
```

**Comment by mp911de** [comment]
`null` keys get rejected now. `null` values are allowed in certain cases. Encoding errors are propagated to the command and no longer cause a timeout. `null` value handling lies in the responsibility of a `RedisCodec`. Encoding errors can break the connection protocol state synchronization and so a connection needs to be closed after running into an `EncoderException`.
