### ISSUE TITLE
Password for trusted store

### ISSUE THREAD

**Issue by maxd** [mp911de/lettuce#292]
Look at this lines: [here](https://github.com/mp911de/lettuce/blob/6c63142ce7125fb14d035485cdc6ccec06eb6223/src/main/java/com/lambdaworks/redis/SslConnectionBuilder.java#L104) and [here](https://github.com/mp911de/lettuce/blob/6c63142ce7125fb14d035485cdc6ccec06eb6223/src/main/java/com/lambdaworks/redis/SslConnectionBuilder.java#L224). As you can see right now impossible to specify password for trusted store.

Could you please add such ability?

**Comment by mp911de** [comment]
Ack. Related to #249

**Comment by mp911de** [comment]
Done.
