### ISSUE TITLE
How to abort/cancel execution of command?

### ISSUE THREAD

**Issue by maxd** [mp911de/lettuce#297]
For example I have a database with 10M keys. I run `KEYS *` command and lettuce start receiving keys from Redis server. Now I want to abort/cancel execution of this command. How to do it?

I have tried to use `RedisFuture#cancel` command but after call it I still see that lettuce receiving keys from Redis server.

**Comment by mp911de** [comment]
Hi, 
don't run `KEYS *` in production. It will block Redis and create a congestion so other clients need to wait until the command finishes - and it may blow up your memory. Commands sent once to Redis cannot be canceled in a clean way. The only thing I could imagine is closing the connection. `cancel()` is only useful when dealing with reconnect as queued commands that are canceled don't get retried upon reconnect.

**Comment by maxd** [comment]
I agree with you about KEYS command but I want to implement REPL console in my application. As you understand in this case user can type any command (include KEYS) and I want to have a way to abort execution of any user command.

I think I will close connection to abort command.

Thank you! :)
