### ISSUE TITLE
Async command does not respond if called in response to PubSub notification

### ISSUE THREAD

**Issue by eileenh** [mp911de/lettuce#298]
Prerequisites:
Test assumes that redis is available on "redis://localhost:6379"
This reproduces when run on debian jessie in docker, but not on a mac.
Run against redis 3.0.3 (did not try other versions)
Lettuce 4.1.2.Final or 4.2.0.Final

Repro:
https://gist.github.com/eileenh/180964d7629984a9b2e12a895c7de6e6
Summary:
1. Create several connections to redis
2. Also create 2 pubSub connections (one for publishing and one for subscribing)
3. Subscribe to pubsub notifications
4. rpush a string
5. expire the entry for some point in future
6. publish a notification
7. When receiving pubsub notification, do lrange command on same thread
(hang)

Actual behavior:
Test does not complete.

Expect:
Test should complete and pass. 

Trace level logs of a test run also available in the gist.

**Comment by eileenh** [comment]
Apologies for the slightly wonky test - this is a reduction of some actual code we have so it was a little challenging to get to a point where it was smaller than the entire application.

This does not repro on lettuce 4.0.Final, and this is blocking us from upgrading.

**Comment by mp911de** [comment]
Hi @eileenh, 
thanks for the test case. I noticed that you perform a blocking call inside of listener `message` method. 

Each channel I/O is handled by an `EventLoop` thread. The listener notifications are also invoked on the `EventLoop`. So at least one thread is busy with notifying the listener. When invoking a command, the same (or another) `EventLoop` is asked to perform the work but as `EventLoop` threads are already busy they start to expose a blocking/busy behavior.

You can invoke commands from within a listener but you mustn't block. If you're required to use blocking sequences, then use please an own `ExecutorService`.

See also: http://normanmaurer.me/presentations/2014-facebook-eng-netty/slides.html#23.0

**Comment by eileenh** [comment]
Thank you very much for taking a look, and for your explanation. I probably should have thought of it, but it hadn't occurred to me that I could block threads used by lettuce by doing things in the listener.

Seems really weird that it repros in only one of the two environments I tried, and not until lettuce 4.1.2, but I guess that's threading for you.

**Comment by mp911de** [comment]
No worries. These things can happen all over the place as the consequences of blocking calls on the `EventLoop` aren't too obvious.
