### ISSUE TITLE
MONITOR command

### ISSUE THREAD

**Issue by maxd** [mp911de/lettuce#299]
I can run MONITOR command (through creation of custom command) and receive status OK but I don't understand how to receive full response of this command (like output of `redis-cli MONITOR`). Is it possible to do in lettuce?

**Comment by mp911de** [comment]
`MONITOR` can't be used through lettuce. It's a similar thing to Pub/Sub hence it would require an individual listener and handling. The other reason is, the only way how to recover from `MONITOR` is effectively closing the connection.

I've no plans of supporting `MONITOR`.
