### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by fggarcia** [mp911de/lettuce#301]
I'm using Lettuce 4.2.1-Final for some days without any issue, but today throw an exception

com.lambdaworks.redis.RedisException: java.util.ConcurrentModificationException

Sorry for no logs, I will try to reproduce the error.

**Comment by mp911de** [comment]
Can't proceed without a stack trace.

**Comment by mp911de** [comment]
Any update on this ticket?

**Comment by fggarcia** [comment]
No. The issue doesn't appear again. So, you can close this issue.
