### ISSUE TITLE
cannot connect to redis sentinel using Lettuce if one of the sentinels is down

### ISSUE THREAD

**Issue by RahulBabbar** [mp911de/lettuce#304]
Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/lettuce/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the lettuce version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

 

We are unable to connect to redis-sentinel using Lettuce if we provide three sentinels and one of them is down.
If one of the machine goes down, then lettuce is unable to connect to sentinel.
However, if the server is up and running, then it works well, and it seems to give timeouts for new connections.

**Comment by mp911de** [comment]
Fixed by allowing one or more unavailable Sentinels.
