### ISSUE TITLE
Investigate memory leak

### ISSUE THREAD

**Issue by przemyslaw-elias** [mp911de/lettuce#307]
My app using lettuce died today because of full heap triggerring full GC all the time. Heap dump shows that 90% of the old gen (1.8 GB) was taken by Netty event loop group full of io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTasks.

![image](https://cloud.githubusercontent.com/assets/1998966/16669717/4f52c584-4497-11e6-99f8-a68b1cbed711.png)

I've got suspicion that connection to Redis got reset or broken and that's why the heap got filled with write tasks.

Have you encountered similar problems or have any idea what's causing the issue?

**Comment by mp911de** [comment]
Hi, 
I haven't run into such an issue yet. Have you checked the logs for what happened? lettuce usually logs unexpected disconnects.

Usually, when the connection is broken, commands get buffered in the `CommandHandler` with `AsyncCommand` as top-level item until the reconnect retries all commands. It might be an issue related to back-pressure that you're producing more commands than netty is able to send.

It _could_ also be that the `EventLoop` used by netty for this particular channel is busy/blocked and this could be an explanation why the channel can't keep up with sending. Do you also have a Thread dump?

You can limit the queue size of commands that should get written using [`ClientOptions`](https://github.com/mp911de/lettuce/wiki/Client-options#request-queue-size) but that's just a patch that protects your application but does not solve the issue.

**Comment by przemyslaw-elias** [comment]
Logs had nothing suspicious inside - no entries on any connection reset nor broken. Unfortunatelly I didn't take thread dump - my bad. It could have answered the question whether something blocked EventLoopGroup, I'll be monitoring this and also will review other uses of EventLoopGroup since we share one between Lettuce and other tasks.

**Comment by mp911de** [comment]
Maybe you want to create a ticket at https://github.com/netty/netty. I think that could be of interest for those guys.

**Comment by mp911de** [comment]
Any update on this ticket?

**Comment by przemyslaw-elias** [comment]
We are still investigating and will probably sunset Redis in favor of Hazelcast anyway. The pitty is Lettuce won't work with epoll and this for sure makes Netty produce more garbage.

**Comment by asgs** [comment]
@przemyslaw-elias did you happen to solve the Netty Event group issue?

**Comment by przemyslaw-elias** [comment]
I can't remember now. I think it could have been related to Redis server closing connections after short time.

**Comment by varknull** [comment]
Just to report, I had a similar issue with full GC on the old gen caused by Netty event loop. What happened in my case were redis connection resets which lead lettuce request queue to grow and somehow that triggers the GC. I solved the full GC by limiting `requestQueueSize` even if the source issue here is Redis.
