### ISSUE TITLE
Redis Cluster Client ends up in a bad state during failover/networking partition

### ISSUE THREAD

**Issue by long-xuan-nguyen** [mp911de/lettuce#308]
This is a continuation of https://github.com/mp911de/lettuce/issues/262

I've applied the fix and it has been working well for the last 3 weeks (3 networking events without issue) until a couple of days ago.  This could also be related to https://github.com/mp911de/lettuce/issues/277 but i dont see the fix applied to 4.1 branch so i am not sure if this bug is in 4.1 branch

Anyway, this time, we have a master failover. One of the slave nodes got promoted and out of 30 hosts, about 2 hosts didn't recover and any future command sent into the client will have timeout exception

I'll collect some log and update the issue here. Do you think this is related to https://github.com/mp911de/lettuce/issues/277  and any reason why the fix was not applied to 4.1 branch?

**Comment by mp911de** [comment]
4.1.3 was never released (and won't be released). Please use lettuce 4.2.1.

Which client version are you using right now? If 4.1.x or 4.2.0, then please upgrade to 4.2.1.

I'm still surprised that I haven't received #277 as bug report earlier. One thing that bugs me here is that most probably the slave connection wasn't used before. #277 is only applicable to connections that existed and were used before and that got disconnected.

**Comment by mp911de** [comment]
Any update on this ticket?

**Comment by mp911de** [comment]
I found another issue with #315 that could lead in fast reconnect-scenarios to an out-of-sync state.

**Comment by mp911de** [comment]
Closing this ticket because it seems inactive.
