### ISSUE TITLE
ERROR io.netty.util.ResourceLeakDetector , Running inside threads.

### ISSUE THREAD

**Issue by laxmi-narayan-nitdgp** [mp911de/lettuce#311]
Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/lettuce/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the lettuce version and environment so it's obvious which version is affected
- [x] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

 

I have 50 threads running for infinite time and inside each thread I am creating connection and closing connection inside thread itself.

But while running code for the first time , It gives me following error and code executes gracefully.

[802] ERROR io.netty.util.ResourceLeakDetector  - LEAK: You are creating too many HashedWheelTimer instances.  HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.

All of my threads are running for infinite time with interval of 30 second ,Once they start again I do not see any of such issue.

Below is code snippet which I am using to create connection with redis.

           RedisClient redisClient = RedisClient.create("redis://@localhost:6379/0");
            StatefulRedisConnection<String, String> connection = redisClient.connect();
           RedisCommands<String, String> syncConnection = connection.sync();

lettuce - 4.2.0.Final.
redis   - 3.0.7
Java Version - Oracle Java8

**Comment by mp911de** [comment]
Don't create too many `RedisClient` instances. You can create multiple connections with `redisClient.connect()`. The use cases for creating multiple connections are very limited (usage of transactions or blocking commands are the most common). lettuce connections are designed to be long-lived and shared amongst threads.

In short: The message above is correct.
