### ISSUE TITLE
Metrics: WithLatency.sent(long) never called

### ISSUE THREAD

**Issue by HaloFour** [mp911de/lettuce#314]
I'm trying to use a custom `CommandLatencyCollector` to record metrics regarding the execution time of commands through Lettuce.  I'm finding that the `completionLatency` argument is invariably a very large number.  Tracking through the code in Lettuce I'm finding that while `WithLatency#firstResponse` and `WithLatency#completed` are being called, `WithLatency#sent` never is, so the value remains the initial value of `-1`.  The `completionLatency` argument is calculated from `WithLatency#getCompleted` - `WithLatency#getSent`.

**Comment by mp911de** [comment]
Thanks, that's fixed now.
