### ISSUE TITLE
Deadlock when using cluster connection

### ISSUE THREAD

**Issue by guperrot** [mp911de/lettuce#326]
Hi,

We had our first dead lock caused by lettuce in a production service. It happened only once so far (have used the library in production for 1 month). We use the version `4.2.0.Final`.

Basically the dead lock happened in lettuce internals between the `lettuce-eventExecutorLoop` thread and the `lettuce-nioEventLoop` thread.

I attach to this issue a filtered `jstack` output showing the deadlock. In that state all API calls are never returning when using the async API.

[lettuce-deadlock.txt](https://github.com/mp911de/lettuce/files/398372/lettuce-deadlock.txt)

**Comment by mp911de** [comment]
Thanks for the bug report. I'll take care of this.

**Comment by mp911de** [comment]
That's fixed and will be released with 4.2.2 and 4.3.0.

**Comment by guperrot** [comment]
Hi, that was fast, thanks. I will watch for the upcoming release.
