### ISSUE TITLE
MasterSlaveTopologyProvider does not recognize slave if slave ip uses IPv6 address

### ISSUE THREAD

**Issue by maksimlikharev** [mp911de/lettuce#329]
windows port of redis, lettuce 4.2.1.Final.

2 redis running on the same box, one master another slave, windows, this is my sandbox

```
StatefulRedisMasterSlaveConnection<String, String> connection = MasterSlave.connect(client,
   new Utf8StringCodec(),
   RedisURI.builder().redis(config.getHost(), config.getPort()).build());
```

host and port points to master

replication info returned as

# Replication
role:master
connected_slaves:1
slave0:ip=::20f8:1400:0:0,port=6380,state=online,offset=12132,lag=1
master_repl_offset:12132
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:2
repl_backlog_histlen:12131

slave not recognized

**Comment by mp911de** [comment]
Thanks for the bug report. That's fixed now.
