### ISSUE TITLE
Provide API and visibility in order to extend RedisClient and its connections

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#33]
Some scenarios and users need to alter behavior of the redis client (see #31). This is currently not possible. It's required therefore to be able to extend the client and inject custom behavior. 

This can be implemented by subclassing RedisClient and providing own implementations of the Redis...ConnectionImpl classes.

**Comment by mp911de** [comment]
@kichik, this one is for you. HTH

**Comment by kichik** [comment]
Thanks Mark! This will make it super easy for us to fix such issues in the future without reflection voodoo.
