### ISSUE TITLE
Connection to newly added node is initially unavailable with validateClusterNodeMembership: false.

### ISSUE THREAD

**Issue by oklahomer** [mp911de/lettuce#340]
This issue was previously discovered in another question-marked issue #339 .
Below shows detailed context and error content.

lettuce version
====
[4.2.1](https://github.com/mp911de/lettuce/releases/tag/4.2.1.Final)

Contextual information
====
To maximize the availability, I applied some changes to client options: ClusterClientOptions and ClusterTopologyRefreshOptions.
Current settings are shown below:
```Java
ClientResources clientResources = DefaultClientResources.builder().build();
List<RedisURI> redisURIs = ...;
RedisClusterClient redisClusterClient = RedisClusterClient.create(clientResources, redisURIs);

ClusterTopologyRefreshOptions topologyRefreshOptions =
        ClusterTopologyRefreshOptions.builder()
                                     .enablePeriodicRefresh(INTERVAL_IN_SECONDS, TimeUnit.SECONDS)
                                     .enableAllAdaptiveRefreshTriggers()
                                     .build();

ClusterClientOptions clusterClientOptions =
        ClusterClientOptions.builder()
                            .validateClusterNodeMembership(false) // To acknowledge brand new nodes
                            .topologyRefreshOptions(topologyRefreshOptions)
                            .build();

redisClusterClient.setOptions(clusterClientOptions);
```
In this modification, ```ClusterClientOptions#validateClusterNodeMembership``` is set to false to acknowledge brand new nodes with new *host:port* regarding #109.
However, ```ClusterClientOptions#closeStaleConnections``` is left with default value: **true**. (Just got to have a hunch that this is somehow related...)

Simplest possible steps to reproduce
====
Create lettuce instance with above settings, add nodes to redis cluster, reshard, and an [exception](https://gist.github.com/oklahomer/3101a1b6c623056eb359223cf67be625) is thrown. It is thrown only once and later operations seem to run normally and as expected.

Thanks in advance.

**Comment by mp911de** [comment]
The reason for the failure: The newly created connection is opened in the same thread (`EventLoop`) that is assigned to the connection itself. Opening a new connection will assign a different `EventLoop` which is a different thread and so it eventually works. The solution should be retrying using the computation thread pool.

**Comment by mp911de** [comment]
That's fixed now.
