### ISSUE TITLE
ClusterCommand counts executions instead of redirections and completes a command too early

### ISSUE THREAD

**Issue by Spikhalskiy** [mp911de/lettuce#344]
From [docs](https://github.com/mp911de/lettuce/wiki/Redis-Cluster-%284.0%29#refreshing-the-cluster-topology-view):

> By default, commands are executed up to 5 times (up to 4 redirects) until the command execution is considered to be failed.

From code:

```
        public static final int DEFAULT_MAX_REDIRECTS = 5;
        private int maxRedirects = DEFAULT_MAX_REDIRECTS;
        /**
         * Number of maximal cluster redirects ({@literal -MOVED} and {@literal -ASK}) to follow in case a key was moved from
         * one node to another node. Defaults to {@literal 5}. See {@link ClusterClientOptions#DEFAULT_MAX_REDIRECTS}.
         *
         * @param maxRedirects the limit of maximal cluster redirects
         * @return {@code this}
         */
        public Builder maxRedirects(int maxRedirects) {
            this.maxRedirects = maxRedirects;
            return this;
        }
```

This is a prety misleading name. To make a client which makes up to 4 redirects I need to set maxRedirects parameter to 5.

Would be good to rename maxRedirects to maxAttempts and specify in the javadoc that a client with maxAttampts would make up to maxAttempts - 1 redirects.

**Comment by mp911de** [comment]
Thanks for your ticket. The idea behind the configuration item is to control the number of redirects. Attempts fit also to failed commands that could be reattempted due to I/O errors. I think the appropriate fix to this issue is fixing the `maxRedirects - 1` behavior so it's no longer `-1` but reflects the true number of `-MOVED` and `-ASK` redirects.

**Comment by mp911de** [comment]
That's fixed now.
