### ISSUE TITLE
Consider reworking RedisFuture to abstract class extending CompletableFuture

### ISSUE THREAD

**Issue by Spikhalskiy** [mp911de/lettuce#347]
Current API with RedisFuture as interface extending CompletionStage<V>, Future<V> is uncomfortable and doesn't make it possible to really use power of CompletionStage and CompletableFuture.

Example:

This works fine:
```
    private RedisAdvancedClusterAsyncCommands<String, String> asyncCommands;
    @Override    
    public Future<String> get(String key) {
        return asyncCommands.get(key);
    }
```

This already doesn't:
```
    private RedisAdvancedClusterAsyncCommands<String, String> asyncCommands;
    @Override
    public Future<String> get(String key) {
        return asyncCommands.get(key).thenApply(s -> {return s + "";}); //it's not a future, non compilable
    }
```

When I use async Lettuce API I actually do something like:
```
    private RedisAdvancedClusterAsyncCommands<String, String> asyncCommands;
    @Override
    public CompletableFuture<String> get(String key) {
        return ((CompletableFuture<String>)asyncCommands.get(key)).thenApply(s -> {return s + "";});
    }
```

Which is disgusting. So, obviously extending CompletionStage is not enough to use fine API related to CompletableFuture.

What about reworking RedisFuture to something like:
```
public abstract class RedisFuture<V> extends CompletableFuture<V> {
    abstract String getError();
    abstract boolean await(long timeout, TimeUnit unit) throws InterruptedException;
}
```

It would make it possible to write really good code for java8 with full CompletableFuture support.

**Comment by mp911de** [comment]
That's not possible. `RedisFuture` is an interface, like `CompletionStage`. Why don't you call `RedisFuture.toCompletableFuture()`?

**Comment by Spikhalskiy** [comment]
Sure, but what's the problem to make abstract class from it? In any case, all implementors extend CompletableFuture class. Instead of this they could extend RedisFuture.

> Why don't you call RedisFuture.toCompletableFuture()
Shame on me, I didn't know about CompletionStage#toCompletableFuture.

**Comment by mp911de** [comment]
`RedisFuture` is an interface for various reasons. Interfaces are easier to mock and they retain certain options related to implementations. The current interface-based implementation does not require the implementation to be a `CompleteableFuture`, just implementing the API contract given by `CompletionStage` and `RedisFuture`.

**Comment by Spikhalskiy** [comment]
Ok, in case if it's important to you to keep it as an interface - ```CompletionStage#toCompletableFuture()```- do the work for me. Thank you.
