### ISSUE TITLE
Looking for ability to define shared HashedWheelTimer with custom resolution

### ISSUE THREAD

**Issue by plokhotnyuk** [mp911de/lettuce#354]
Please add ability to define subj for the client, because now I should extend RedisClient with following overload to reuse shared timer in our Scala app:

```
class RedisClientWithTimer(resources: DefaultClientResources,
                           timer: HashedWheelTimer) extends RedisClient(resources, new RedisURI) {
  override def connectionBuilder(handler: CommandHandler[_, _], connection: RedisChannelHandler[_, _],
                                 socketAddressSupplier: Supplier[SocketAddress], connectionBuilder: ConnectionBuilder,
                                 redisURI: RedisURI): Unit = {
    super.connectionBuilder(handler, connection, socketAddressSupplier, connectionBuilder, redisURI)
    connectionBuilder.timer(timer)
  }
```

**Comment by mp911de** [comment]
Hi @plokhotnyuk, 

thanks for the ticket. I've been thinking a couple times about sharing `HashedWheelTimer` with `ClientResources`. I'm always coming back to the nature that the timer is single-threaded. If the timer thread is busy, reconnect won't work. Please note that a new timer is created in `com.lambdaworks.redis.AbstractRedisClient.<init>`, so each time you construct a `RedisClient`, a new `HashedWheelTimer` is instantiated.

I'll take your request into consideration.

**Comment by mp911de** [comment]
That's implemented now.
