### ISSUE TITLE
Is connection pooling required?

### ISSUE THREAD

**Issue by ahmednasir91** [mp911de/lettuce#360]
This is not a bug-report but rather a question.

We are having issues with Redis Connect times, and we see connection socket timeout exception  in logs and connection spikes, the connections jump from ~1000 to ~10000 and then go down again, hence impacting the performance.

We have multiple spring boot based microservices, along with redis connection pooling, and we are using the default connector for redis. Some services have 3000 max-connections per instance. We are not using any transaction/blocking commands. In total we have around 250k read requests/min.

We found lettuce and have decided to use it, what do you recommend, should we use connection pooling in lettuce, or we will be able to handle the load without connection pooling? from the docs it seems we don't need connection.
Also, will lettuce be able to help us in getting rid of the socket timeout issues?

**Comment by mp911de** [comment]
Hi @ahmednasir91, 

that's a lot of connections. If you don't use any transactions/blocking commands, then there is almost no reason for connection pooling. Lettuce connections are thread-safe and can be shared amongst multiple threads. Lettuce is an event-driven client that handles commands asynchronously. The synchronous wrapper synchronizes commands (with applying a timeout) and you get almost a look and feel as if you would use a fully synchronous client.

Socket timeouts can originate in too many TCP connections. Same can happen if you would spin up that many connections with lettuce. Ideally, you operate on one Redis connection per application.

If using Spring Data Redis, you can use lettuce 3.x. If you don't use Spring Data Redis, then you can use any version of lettuce with Spring Boot.

**Comment by ahmednasir91** [comment]
Thanks @mp911de 

Yes we are using Spring Data Redis and will be using lettuce 3.x.

Do you think 1 connection per application (i would say per instance) will be sufficient as we have around 80k reads + writes / min from one of our application instance?

We really need to avoid the connection spikes and the timeouts, we don't see spikes in number of incoming requests to our services but we are unable to find the cause why application requests too many connections at one time.

**Comment by mp911de** [comment]
Redis user-space operations are single-threaded so there is no need for throughput reasons to have more than one connection. A single thread can execute about 10.000 Redis commands (`GET`, `SET`) per second. Using 6 to 8 threads this number rapidly goes up to 80kOps/sec to 100kOps/sec.

I'd propose to enable `LettuceConnectionFactory` and run some performance tests. There's not much to configure - except for timeouts. You could run `LettuceConnectionFactory` with pooling but that again introduces the pattern you want to avoid.

**Comment by ahmednasir91** [comment]
Makes sense, thanks very much,

**Comment by ryumer** [comment]
@mp911de Hi, I know this issue is closed but I see this question very relevant.

I am using spring-boot 2.0, spring-data-redis and lettuce. I have been trying to understand the motivation behind using a shared connection and I believe I am missing some point. We are using `@Cacheable` annotations and by I see that a sharedConnection is used, but its `RedisSentinelCommands` is used instead of `RedisSentinelAsyncCommands`, as expected.

Now, how does a single shared connection does not suffer from network lag when used in sync mode? As I understand, it awaits the response of a command before sending another one.

**Comment by mp911de** [comment]
> We are using @Cacheable annotations and by I see that a sharedConnection is used, but its RedisSentinelCommands is used instead of RedisSentinelAsyncCommands, as expected.

A single connection may be operated through different API's. In a multi-threaded environment, it does not really matter which API is used. You'd use async commands only to increase efficiency within a single thread or if you follow an async programming model.

> Now, how does a single shared connection does not suffer from network lag 

True. From a global perspective, that's independent of the API you use. From a Thread perspective, you want to use async commands to minimize latency in a synchronous flow.

> As I understand, it awaits the response of a command before sending another one.

Depends on your perspective. Looking from a single-threaded perspective using the synchronous API that's true. Single-threaded using the asynchronous API that statement is no longer true. Also, from a multi-threaded perspective (regardless of the used API) the statement is not true either.

Commands are sent as soon as they hit the connection. See https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing for more details.

**Comment by patkovskyi** [comment]
Sorry to bring this up again.

> If you don't use any transactions/blocking commands, then there is almost no reason for connection pooling.
What if I use pipelining and setAutoFlushCommands(false)? I assume I can't have a single shared connection in a multi-threaded environment then. Is pooling the right way to avoid having one StatefulRedisClusterConnection per each thread in this case?

**Comment by mp911de** [comment]
It basically boils down to prevent race conditions and shared state issues. If you can guarantee that a connection state change does not affect other concurrent processes, then you can get away with a single connection. With great power comes great responsibility.

**Comment by patkovskyi** [comment]
The main thing I don't understand is how flushCommands() works on a shared connection in multi-threaded environment.

Say I have 2 threads (T1 and T2) and they own 2 different instances of RedisAdvancedClusterAsyncCommands (R1, R2), which are retrieved from a single StatefulRedisClusterConnection which has setAutoFlushCommands(false). 

T1 is going to issue commands C1, C2 via R1, and then call R1.flushCommands().
T2 is going to issue commands C3, C4 via R2, and then call R2.flushCommands().

What if R1.flushCommands() is called after T2 issued C3 but before it issued C4 (and before it called R2.flushCommands())? Will C3 be written to the transport layer?

**Comment by patkovskyi** [comment]
**Upd:** I checked the source code and saw that flushCommands() on API object calls `connection.flushCommands()`. This tells me that C3 will be flushed immediately, but it probably won't break awaitAll().

I wonder then: how does default Lettuce pipelining work? Would it make sense for us to use autoFlushCommands == true and rely on it (we only batch 12 hgetall requests per request to our service)?
