### ISSUE TITLE
Missing INCR option for ZAddArgs.

### ISSUE THREAD

**Issue by christophstrobl** [mp911de/lettuce#367]
`ZAddArgs` is missing the `INCR` option.

Further more it is not possible to construct an option chain defined as `[NX|XX] [CH] [INCR]` by using `ZAddArgs.Builder`.

**Comment by mp911de** [comment]
`ZAddArgs` does not have the `INCR` option as `INCR` changes the return type to bulk string (`Double` in the case of lettuce). There's a dedicated `zaddincr` method but it misses `ZAddArgs`. Adding `Double zaddincr(K key, ZAddArgs zAddArgs, double score, V member);` should fix the issue, right?

**Comment by christophstrobl** [comment]
missed the `zaddincr` method but yes - adding `ZAddArgs` should fix it.

**Comment by mp911de** [comment]
That's fixed with 4.3.0.
