### ISSUE TITLE
Will the library also support a bounded queue flavor

### ISSUE THREAD

**Issue by seno5979** [mp911de/lettuce#372]
Just asking if we can have another flavor of queue instead ConcurrentLinkedQueue (unbounded queue).

If the network issue is occur for a long time, it will exhausting all the memory. With the bounded queue, we might have option to ignore the message when the queue is full.

**Comment by mp911de** [comment]
Lettuce implements a bounded queue behavior that's configurable. See https://github.com/mp911de/lettuce/wiki/Client-options#request-queue-size and https://github.com/mp911de/lettuce/wiki/Client-options#disconnected-behavior to control the queue size/disconnected behavior.

**Comment by seno5979** [comment]
Nice. Thanks for the information. I will try it.
