### ISSUE TITLE
StatefulRedisConnection returns RedisCommands instead of RedisPubSubCommands

### ISSUE THREAD

**Issue by szabowexler** [mp911de/lettuce#374]
Context: lettuce 4.2.2.Final, Java api.

This makes it quite difficult at present to do pubsub with Sentinel enabled. Was this intentional? 

This question could also be phrased slightly differently. Instead, it could be: why is it that RedisPubSubCommands inherits from RedisCommands, instead of vice versa?

**Comment by mp911de** [comment]
Not sure I follow about the Sentinel part. Using a `redis-sentinel://sentinel1,sentinel2,sentinelN?sentinelMasterId=…` URI with any `RedisClient.connect`/`RedisClient.connectPubSub` method will use Redis Sentinel look up the according master. Works for regular and Pub/Sub connections.

The reason for the distinction between `RedisCommands` and `RedisPubSubCommands` is that once a Redis connection enters a Pub/Sub state (`SUBSCRIBE`, `PSUBSCRIBE`) it's no longer usable for other Redis commands. Therefore, Pub/Sub with subscription methods is an add-on to normal Redis connections.

**Comment by szabowexler** [comment]
Perhaps I'm misunderstanding what's possible. Consider the following situation: we have a set of sentinel instances running, which are monitoring a master and two slaves. We connect a client using a sentinel URI, and subscribe. 

While we are subscribed, the master becomes impaired. Sentinel detects this, and promotes one of the slaves to be the new master, automatically slaving the old slave to the new master.

I would expect in such a situation that the PubSub connection would break (because of the impaired master), and would automatically be established once the new master is elected, without my having to do anything. Is that what will happen? Based on my understanding, I'd have to manually implement the reconnect.

Regarding the distinction: I'm not sure I see how that makes sense. A `RedisPubSubCommands` object is also a `RedisCommands` object -- because of inheritance, the relationship described isn't obvious from the class hierarchy. Given that, I don't see why it makes sense to separate them out. Wouldn't it make more sense to have `RedisPubSubCommands` be treated like every other command set, and just have the underlying command dispatcher throw an exception (i.e. fail fast) if a client ever tried to do a regular command while subscribed via PubSub?

**Comment by mp911de** [comment]
> I would expect in such a situation that the PubSub connection would break (because of the impaired master), and would automatically be established once the new master is elected, without my having to do anything. Is that what will happen? 

Yes, lettuce will ask the [configured and available Sentinels](https://github.com/mp911de/lettuce/blob/master/src/main/java/com/lambdaworks/redis/RedisClient.java#L845) to obtain the new master IP address.

> Based on my understanding, I'd have to manually implement the reconnect.
How so?

**Comment by szabowexler** [comment]
Ah, I see - it was a misunderstanding of how reconnects are done. Never mind -- thanks for your time. :)
