### ISSUE TITLE
RedisAdvancedClusterAsyncCommandsImpl.msetnx reports true if any key was set not all keys

### ISSUE THREAD

**Issue by mjaow** [mp911de/lettuce#376]
The website (http://redis.io/commands/msetnx) clarify that msetnx return 1 only if all keys were set.It means that the msetnx method  returns true only if all slots of msetnx returned true.But in your code,it returns true if one of them returned true

**Comment by mp911de** [comment]
While this is a bug in the return type you should be aware this is a distributed operation. `MSETNX` executed on a single node with a mixed set of existing and non-existing keys will not set the non-existing keys if a key of the operation already exists. That's different with the `MSETNX` cluster operation. It can't guarantee atomicity so some keys might get set on one node while another node does not set any keys at all.
