### ISSUE TITLE
Allow Pub/Sub subscriptions on a node selection within Redis Cluster

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#385]
Redis Cluster and Pub/Sub works in two different ways. 
1. User-space Pub/Sub notifications are distributed across cluster nodes. That's a broadcast to all nodes which makes it sufficient to subscribe on one node only to receive messages
2. Key-space Pub/Sub broadcasts notifications only node-local. If a key expires, the message is not broadcasted to the whole cluster. A subscriber is required to subscribe to all relevant nodes to receive the keyspace message.

Key-space notifications require a client to subscribe to all nodes. Cluster topology changes make it hard for applications to follow changes and delete invalid subscriptions/create new subscriptions.

lettuce should provide a mechanism within Cluster Pub/Sub to either subscribe to only one node or to subscribe to multiple nodes and so being able to receive key-space notifications from selected nodes. Selection could be done similar to the `NodeSelection` API.

**Comment by mp911de** [comment]
Node-Selection Pub/Sub comes with node-local listeners (`getConnection(…).addListener(…)`) and node event propagation towards `StatefulRedisClusterPubSubConnection`.

Topology change tracking and topology change adoption resulting in subscription to newly added nodes is not part of this ticket.

**Comment by jigneshmpatel** [comment]
I am trying to implement this solution but it is not working. I request you to look into this discussion.
https://github.com/redis/lettuce/discussions/2856
