### ISSUE TITLE
Does lettuce support sharding (several masters)?

### ISSUE THREAD

**Issue by porunov** [mp911de/lettuce#398]
Hello,

I have 2 masters with 2 slaves. I need to be able write to master nodes depending on the key (using hash) and read from slaves also using hash. Is it possible to use lettuce for such a case? 

Sincerely,
Alexandr

**Comment by mp911de** [comment]
Hi @porunov,

lettuce supports only built-in Redis operation modes: Standalone (one Redis node), Master/Slave (one slave, multiple nodes), Master/SlaHi @porunov,

lettuce supports only built-in Redis operation modes: Standalone (one Redis node), Master/Slave (one slave, multiple nodes), Master/Slave managed by Redis Sentinel and Redis Cluster (multiple masters and slaves). Lettuce does not provide a sharding layer on top of a plain Master/Slave configuration. You can use sharding but only with Redis Cluster.ve managed by Redis Sentinel and Redis Cluster (multiple masters and slaves). Lettuce does not provide a sharding layer on top of a plain Master/Slave configuration. You can use sharding but only with Redis Cluster.

**Comment by porunov** [comment]
Hello Mark,

Thank you for the response. 

I want to load balance read requests among slave nodes (either with Master/Slave mode or Redis Cluster node). I tried to use ReadFrom.SLAVE but it seems that it chooses a random slave node and reads only from it. Is it possible to change it (to load balance among slaves) or get a list of slave nodes to implement Round Robin reads?

**Comment by mp911de** [comment]
Redis Cluster performs a node selection first and caches the selected read candidates until the topology is refreshed. Master/Slave selects the read candidates upon each request. Both variants use a list of nodes that are in some order:

* Redis Cluster: Ordered by response latency.
* Master/Slave without Sentinel: Ordered by response latency.
* Master/Slave with Sentinel: Ordered master first, then all slaves in the order as reported by `SENTINEL SLAVES`.

You can implement round robin or any other strategy by extending from `ReadFrom` and implement `List<RedisNodeDescription> select(Nodes nodes)`.

It could make sense to disable read candidate caching for Redis Cluster but it will slow down the application as read candidates have to be determined by slot-hash and then applying `ReadFrom` selection.

**Comment by porunov** [comment]
Thank you very much for help!
It is great. I am closing the issue because you have answered all questions :)
