### ISSUE TITLE
Getting blank value while using codec.

### ISSUE THREAD

**Issue by abhishekmaheshwari86** [mp911de/lettuce#399]
Hi i am using below code to encode and decode value. Some time i am getting   "testZero length value" while decoding values. Please let em know what is wrong in this code.

    RedisCodec<ByteBuffer, V> codec = new RedisCodec<ByteBuffer, V>()
        {
            @Override
            public ByteBuffer decodeKey(ByteBuffer bytes)
            {
                byte[] b = new byte[bytes.remaining()];
                bytes.get(b);
                return ByteBuffer.wrap(b);
            }

            @Override
            public V decodeValue(ByteBuffer bytes)
            {
                byte[] b = new byte[bytes.remaining()];
                bytes.get(b);
                if(b.length==0){
                    LOGGER.error("testZero length value");
                }
                return valueCodec.decode(ByteBuffer.wrap(b));
            }

            @Override
            public ByteBuffer encodeKey(ByteBuffer key)
            {
                byte[] b = new byte[key.remaining()];
                key.get(b);
                if(b.length==0){
                    LOGGER.error("testZero length key");
                }
                return ByteBuffer.wrap(b);
            }

            @Override
            public ByteBuffer encodeValue(V value)
            {
                return valueCodec.encode(value);
            }
        };

**Comment by mp911de** [comment]
There's nothing wrong with your code. Redis can store empty values. Empty values are different from absent values.

**redis-cli**

```
127.0.0.1:6379> set key ""
OK
127.0.0.1:6379> get key
""
```

**Telnet**

```
elnet localhost 6379
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET key
$0

```
