### ISSUE TITLE
Every clustering example shows connecting to single node how is this client useful in a real world clustered environment? 

### ISSUE THREAD

**Issue by steowens** [mp911de/lettuce#400]
According to the documentation the URI only accepts 1 host.  But in a real world scenario the cluster may be gaining and loosing hosts all the time.  RedisClusterclient is a very expensive resource, and should be maintained.  So my question is if we have a redis cluster with hosts potentially coming and going, how is having to set a URI for an active host realistic for a factory bean where the host uri is given in a config?  Seems to me this should take the list of hosts in the cluster or a subset thereof and try to connect to one of them, succeeding on the first node in the list that responds.

```java
    /**
     * Factory Bean for {@link RedisClusterClient} instances. Needs either a {@link URI} or a {@link      RedisURI} as input and allows
     * to reuse {@link com.lambdaworks.redis.resource.ClientResources}. URI Format: {@code
     *     redis://[password@]host[:port]
     * }
     * 
     * {@code
     *     rediss://[password@]host[:port]
     * }
     *
     * @see RedisURI
     * @see ClientResourcesFactoryBean
     * @author Mark Paluch
     * @since 3.0
     */
```

**Comment by mp911de** [comment]
Thanks for raising this issue. I created #401 to fix the single URI issue in `RedisClusterClientFactoryBean`. There are two workarounds right now:

1. Override `RedisClusterClientFactoryBean.createInstance` to create `RedisClusterClient` by passing in multiple `RedisURI`s
2. Provide an own factory/`@Bean` that constructs `RedisClusterClient` as you require it.

I will review and revise lettuce documentation. You might also take a look on [Spring Data Redis](http://docs.spring.io/spring-data/redis/docs/current/reference/html/) that integrates with a couple of Spring components.

**Comment by mp911de** [comment]
I updated the wiki with more multi-node examples. With lettuce 4.4.0/5.0.0 you will be able to pass in a multi-node RedisURI (`redis+tls://password@host1:6379,host2:6380`) to `RedisClusterClient` or use multiple nodes with `RedisClusterClientFactoryBean`.
