### ISSUE TITLE
Support SET NX with timeout

### ISSUE THREAD

**Issue by nosideeffects** [mp911de/lettuce#404]
There is currently no way to issue the following commands in 4.x:

```
SET key value NX 60
SET key value NX PX 60000
```

**Comment by mp911de** [comment]
`SET key value NX 60` is not a valid command. `NX` does not accept any arguments.

Have you tried `sync.set("key", "value", SetArgs.Builder.nx().px(60000))` (`RedisStringCommands#String set(K, V, SetArgs);`)?

**Comment by nosideeffects** [comment]
I had not tried that. That works for my purposes. Thanks! I guess I was just expecting to see a typed version with a boolean return.
