### ISSUE TITLE
Fail to second call pool.borrowObject() using StatefulRedisMasterSlaveConnection in 4.3.0.Final

### ISSUE THREAD

**Issue by krisjey** [mp911de/lettuce#411]
Hello, guys.

I'm trying to change Redis client library Jedis to Lettuce.
Major reason is that data read from the slave.

I rewrote the class for Jedis pooling. and then tested. 
but Lettuce said an error like below. 
```
com.lambdaworks.redis.RedisException: Connection is deallocated and cannot be used anymore.
```
Note.
I used two kind of redis settings. One is master-slave, the other one is redis cluster.
StatefulRedisClusterConnection is working fine.

So, I found some test cases for StatefulRedisMasterSlaveConnection in Lettuce codebase and then change test cases.

https://gist.github.com/krisjey/58f16d4792d606596a47b01a68c2eb3b
<script src="https://gist.github.com/krisjey/58f16d4792d606596a47b01a68c2eb3b.js"></script>

But, Error is same.

Could you give me some clue?

**Comment by mp911de** [comment]
Hi @krisjey 

`ConnectionPoolSupport` suffers from a bug in which the connection proxy (that returns the connection back to the pool on `.close()`) gets into a closed state but is not able to recover from this state once a new connection is obtained from the pool.

As rule of thumb, don't use connection pooling. There are only very few use-cases that make [sense for pooling](https://github.com/mp911de/lettuce/wiki/Connection-Pooling).

If you still require connection pooling, then return your connection yourself to the pool with `pool.returnObject(connection)`.

**Comment by mp911de** [comment]
That's fixed now. You might give `4.4.0-SNAPSHOT` a spin.
