### ISSUE TITLE
io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.

### ISSUE THREAD

**Issue by China-Chenlu** [mp911de/lettuce#413]
### when i use Lettuce , I ran into this exception .Why is that ?
com.lambdaworks.redis.RedisException: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.

**Comment by mp911de** [comment]
Please share the full stack trace. This error usually occurs when the key/value cannot be encoded by  the used `RedisCodec`.
