### ISSUE TITLE
Unexpected 'Invalid database number' exception for database > 15

### ISSUE THREAD

**Issue by ChitraGuru** [mp911de/lettuce#420]
Lettuce Version: 4.2.2.Final

When trying to configure RedisURI, and specify the database, there is a check for the value being <= 15 (https://github.com/mp911de/lettuce/blob/master/src/main/java/com/lambdaworks/redis/RedisURI.java#L1144)

However, it is possible to configure redis to allow more than 16 databases. (http://download.redis.io/redis-stable/redis.conf)
```
# Set the number of databases. The default database is DB 0, you can select
# a different one on a per-connection basis using SELECT <dbid> where
# dbid is a number between 0 and 'databases'-1
databases 16
```

Is there any other reason to disallow databases >15 here?

Thanks.

**Comment by mp911de** [comment]
Good catch. That's a bug.

**Comment by mp911de** [comment]
That's fixed now.
