### ISSUE TITLE
RedisClusterCommands and RedisTransactionalCommands

### ISSUE THREAD

**Issue by maxd** [mp911de/lettuce#422]
[RedisClusterCommands](https://github.com/mp911de/lettuce/blob/master/src/main/java/com/lambdaworks/redis/cluster/api/sync/RedisClusterCommands.java) doesn't extend [RedisTransactionalCommands](https://github.com/mp911de/lettuce/blob/master/src/main/java/com/lambdaworks/redis/api/sync/RedisTransactionalCommands.java) interface. Is it ok?

**Comment by mp911de** [comment]
Indeed. There are no cluster-wide transactions. `RedisCommands` extends `RedisClusterCommands` and `RedisTransactionalCommands` while `RedisAdvancedClusterCommands` extends just `RedisClusterCommands`.

**Comment by maxd** [comment]
Thank you.
