### ISSUE TITLE
4.2.2.Final: Sentinel based MasterSlaveTopologyRefresh fails on impaired instance

### ISSUE THREAD

**Issue by szabowexler** [mp911de/lettuce#424]
I'm running the following setup: 

* One redis master, called `M1`
* One redis slave, called `S1`

The two redis nodes are managed by a sentinel cluster (running on different physical instances):

* Three sentinel nodes, called `G1, G2, G3`

I connect a client using a sentinel redis URI. The client negotiates with `G1, G2, G3`, and successfully determines the initial topology of the cluster, detecting `M1` as the master and `S1` as the slave. I then simulate an impairment event by running `DEBUG SLEEP 100` on `M1` (note that 100 is deliberately set higher than my sentinel master impairment timeout to trigger a failover). `G1, G2, G3` detect the impairment, `+odown` is triggered, and a failover occurs. 

On the client side, the `SentinelTopologyProvider` is triggered, and a topology lookup is kicked off. At this point, `M1` is impaired and not handling connections, and `S1` has been promoted, and is now the master of a standalone cluster. We would expect the topology provider to return `S1` as the singleton master.

Instead, however, it returns the empty set (doesn't return any instances at all). I believe this is because of a bug in the implementation of the `getNodeSpecificViews` method in the `MasterSlaveTopologyRefresh` class. As currently implemented, it looks like this:

```java
long timeout = seed.getUnit().toNanos(seed.getTimeout());
long waitTime = 0;
Map<RedisNodeDescription, Long> latencies = new HashMap<>();

for (Map.Entry<RedisURI, TimedAsyncCommand<String, String, String>> entry : rawViews.entrySet()) {
  long timeoutLeft = timeout - waitTime;

  if (timeoutLeft <= 0) {
    break;
  }

  long startWait = System.nanoTime();
  RedisFuture<String> future = entry.getValue();

  try {

    if (!future.await(timeoutLeft, TimeUnit.NANOSECONDS)) {
      break;
    }
    waitTime += System.nanoTime() - startWait;

    future.get();

    RedisNodeDescription redisNodeDescription = findNodeByUri(nodes, entry.getKey());
    latencies.put(redisNodeDescription, entry.getValue().duration());
    result.add(redisNodeDescription);
  } catch (InterruptedException e) {
    Thread.currentThread().interrupt();
    throw new RedisCommandInterruptedException(e);
  } catch (ExecutionException e) {
    logger.warn("Cannot retrieve partition view from " + entry.getKey(), e);
  }
}

LatencyComparator comparator = new LatencyComparator(latencies);

Collections.sort(result, comparator);

return result;
```

The problem here is in how timeouts are handled. Note that we enumerate raw views in an arbitrary order (so let's say for the sake of argument that we enumerate `M1` and then `S1` as these are the values returned by `G1, G2, G3`). We'll compute the timeout for connections based on the sentinel connection (let it be arbitrarily defined to be `10s`). Then in the loop, we'll wait that length of time for `M1` to respond (it will not, as the node is impaired, and completely offline). Once that time is up (when the awaited future expires), the loop will be broken. At this point, `M1` will not have been added (as it never responded), but because the loop is prematurely broken, _neither will `S1`_, which is now the true master, and unimpaired. 

Observe that the wait time is _shared across all connection attempts_ . I believe this behavior is in error: wait time should probably be checked on a per-connection basis. As-is, this is correct if and only if any impaired nodes are grouped and processed after any healthy nodes, which can not be guaranteed by the implicit ordering of the underlying raw view's enumeration order.

**Comment by szabowexler** [comment]
Two things to note:

1. I'd call this a bug, not an enhancement (not sure about your labeling scheme, but this is _very bad_, and completely removes all of the sentinel failover code's utility, until it's fixed.
2. This problem is still present in [4.3.0.Final](https://github.com/mp911de/lettuce/blob/4.3.0.Final/src/main/java/com/lambdaworks/redis/masterslave/MasterSlaveTopologyRefresh.java#L89-L121), and also [5.0.0.Beta](https://github.com/mp911de/lettuce/blob/5.0.0.Beta1/src/main/java/com/lambdaworks/redis/masterslave/MasterSlaveTopologyRefresh.java#L89-L121).

**Comment by mp911de** [comment]
You raised an interesting point that is applicable for Redis Sentinel and Redis Cluster use. Both phases, establishing connections phase and command result synchronization (`PING` for `MasterSlaveTopologyRefresh` and `CLUSTER NODES` for `ClusterTopologyRefresh`) suffer from sequential processing.

The connection phase is sequential. Latencies to establish node connections sum up over the list of nodes to connect and prolong the connection phase. That's one issue. You mentioned already the second issue: Preliminary termination of result collection if one command exceeds the timeout.

`MasterSlaveTopologyRefresh` is affected by this issue while `ClusterTopologyRefresh` handles timeouts in a better way.

A broken Redis instance is usually not reachable (connection timeout) or the process is down (connection refused). Artificial delays (`DEBUG SLEEP`, `CLIENT PAUSE`) is a specific way how you enforced the node to be considered `+odown` – this isn't the usual case how Redis is down.

Therefore I see this issue as optimization as Redis rarely gets into a state where it accepts a connection but does not respond.

**Comment by mp911de** [comment]
That's implemented for Master/Slave and Redis Cluster.
