### ISSUE TITLE
socketOptions return ClientOptions.Builder

### ISSUE THREAD

**Issue by maxd** [mp911de/lettuce#425]
I have noticed that [socketOptions](https://github.com/mp911de/lettuce/blob/c9e407ae522a88764548205763d6e5c3f79858cb/src/main/java/com/lambdaworks/redis/cluster/ClusterClientOptions.java#L240) method return `ClientOptions.Builder` type but other builder methods return `ClusterClientOptions.Builder`. Is it ok?

**Comment by mp911de** [comment]
Good catch! That's fixed now.
