### ISSUE TITLE
Verify that a stale node connection is closed and reconnect attempts are stopped

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#434]
A connection to a master, that is down, tries to reconnect the node. Once a topology upgrade is performed and the master is no longer part of the cluster, the connection should be closed and connection attempts should be stopped.

**Comment by kojilin** [comment]
Curious if this is same issue.

I'm using RedisClusterClient and found that `RoundRobinSocketAddressSupplier`'s roundRobin property still contains removed node and used by `ReconnectionHandler`. So my log has some 

```
Reconnecting, last destination was /192.168.10.100:1000
Cannot connect: com.lambdaworks.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /192.168.10.102:1000
```

and above `ConnectionWatchdog`'s ip and `Cannot connect:`'s ip are different.

**Comment by mp911de** [comment]
I created #440 to track the issue that `RoundRobinSocketAddressSupplier` may contain less nodes than `Partitions`. `last destination` may be different from `Cannot connect`. `last destination` uses the remote socket address from the host it connected successfully the last time.

Note: If you're updating `Partitions` from outside, call `Partitions.updateCache()` after all modifications. `RoundRobinSocketAddressSupplier` checks for consistency upon each socket address retrieval against the topology read view.

**Comment by mp911de** [comment]
The test `com.lambdaworks.redis.cluster.RedisClusterSetupTest#expireStaleNodeIdConnections` correctly verifies that stale connections are closed. Outside changes to `Partitions` will not close stale connections. That's only happens when `RedisClusterClient#updatePartitionsInConnections` is called (part of the topology refresh).
