### ISSUE TITLE
#Psubscribe pattern subscribing on notification channel  Not working by using redis lettuce Cluster in java 

### ISSUE THREAD

**Issue by govind213** [mp911de/lettuce#437]
This is my subscriber Code :- 

String redisNodes = "redis://IP1:9014,redis://IP2:9006,redis://IP1:9006,redis://IP2:9014,redis://IP3:9006,redis://IP3:9015";
	String[] redisNodeStringArray = redisNodes.split(",");
	
	List<RedisURI> redisURIList = new ArrayList<RedisURI>();
   
	for(String redisMasterNodeString : redisNodeStringArray) {
		redisURIList.add(RedisURI.create(redisMasterNodeString));
	}
	
	RedisClusterClient redisClusterClient = RedisClusterClient.create(redisURIList);      
	StatefulRedisPubSubConnection<String, String> connection = redisClusterClient.connectPubSub();
	RedisPubSubAsyncCommands<String, String> async = connection.async();
	async.addListener(new RedisPubSubListener<String, String>() {
		@Override
		public void message(String s, String s2) {
			System.out.println("Message1: " + s + " : " + s2);
		}

		@Override
		public void message(String s, String k1, String s2) {
			System.out.println("Message: "+s+" Key Changed :" + s2 + " , Event : " + k1.split(":")[1] );
		}
         
		@Override
		public void psubscribed(String s, long l) {
			System.out.println("Subscriber");
		}

		@Override
		public void punsubscribed(String arg0, long arg1) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void subscribed(String arg0, long arg1) {
			// TODO Auto-generated method stub
			System.out.println("Message: Key Changed :" + arg0 + " , Event : " + arg1 );
			
		}

		@Override
		public void unsubscribed(String arg0, long arg1) {
			// TODO Auto-generated method stub
			
		}

	});
    async.psubscribe("__key*__:*");

_______________

This is my Publisher code 👎 

String redisMasterNodes = "redis://IP1:9014,redis://IP2:9006,redis://IP1:9006,redis://IP2:9014,redis://IP3:9006,redis://IP3:9015
";
    
    List<RedisURI> redisMasterURIList = new ArrayList<RedisURI>();
    String[] redisMasterNodeStringArray = redisMasterNodes.split(",");
	for(String redisMasterNodeString : redisMasterNodeStringArray) {
		redisMasterURIList.add(RedisURI.create(redisMasterNodeString));
	}
    
	RedisClusterClient redisMasterClusterClient = RedisClusterClient.create(redisMasterURIList);      
	RedisPubSubAsyncCommands<String, String> connection1 = redisMasterClusterClient.connectPubSub().async();
 
    int i = 0;
    while (i<4){
    	
    	String key = "#test"+new Integer(i).toString(); String value = new Integer(i).toString();
    	System.out.println("Sending data : Key - " + key + "value  - " + value);
    	
    	connection1.set(key,value);
    	
    	i++;
    	Thread.sleep(1000);
    }

I set "config set notify-keyspace-events KEA" on all nodes (Set events put data on __key*__:*  channel )
Here in RedisURIList contains 3 masters and 3 slaves. All nodes are connected to each other.
After running this code , publisher is able to set 2 keys in 1 master server and other 2 keys in other masters but notification is coming from one master only not from others.  Same thing happens when i am setting keys from redis client tool on respective master.

Can anyone please help me why I am not getting notifications from other masters.

Thanks

**Comment by mp911de** [comment]
Redis Keyspace notifications work in Redis Cluster slightly different compared to Redis Cluster Pub/Sub. Keyspace notifications are local to each cluster node and not broadcasted across the whole cluster. This requires a subscription to each cluster node (well, at least each node you're interested in). As of 4.3, that's something you're required to handle on your own by using the topology from `Partitions`, select the appropriate nodes, connect via `RedisClient.connectPubSub` to each node and subscribe to the pattern.

Lettuce 4.4 will provide with #385 an API on `RedisClusterClient.connectPubSub()` to subscribe to a node selection that propagates Pub/Sub messages to one listener. You can give `4.4.0-SNAPSHOT` a try:

```xml
<dependency>
  <groupId>biz.paluch.redis</groupId>
  <artifactId>lettuce</artifactId>
  <version>4.4.0-SNAPSHOT</version>
</dependency>

<repositories>
  <repository>
    <id>snapshots</id>
    <name>Sonatype Snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

The reason why it's a node selection and not all nodes is, that masters and slaves will expire keys and most probably you're not interested in duplicate messages.

**Comment by mp911de** [comment]
Question answered, no futher discussion, so closing this ticket.

**Comment by yaitskov** [comment]
Hi. I have the same problem. 
I am using the latest lettuce 4.3.2 (28-Apr-2017) available from maven central.
PubSub callback is not called at all.


```
      final StatefulRedisPubSubConnection<String, String> pubSubConnection = client.connectPubSub();
        final StatefulRedisConnection<String, String> publishConnection = client .connect();
        final RedisPubSubCommands<String, String> commandListener = pubSubConnection.sync();
        final Rediska rediska = new Rediska(new HashMap<>(),
                new HashMap<>(), publishConnection.sync(),
                commandListener,
                new ConcurrentHashMap<>(),
                new ConcurrentHashMap<>(),
                new DefaultConversionService());

        commandListener.addListener(new RedisPubSubAdapter<String, String >() {
            @Override
            public void message(String key, String value) {
                rediska.publish(RedisKey.of(key), value);
            }
        });

redisSubscribeCommands.psubscribe("__key*__:*"); // + key.raw());
```

At least it should fail with an exception explaining that it is not supported.

**Comment by mp911de** [comment]
@yaitskov You're using `PSUBSCRIBE` so you need to override `message(K pattern, K channel, V message)`.

**Comment by yaitskov** [comment]
Doh! Thanks. You saved my day, but it's really a pitfall, which looks strange in a library which reached version 5!
