### ISSUE TITLE
RedisClusterClient  CDI Problem

### ISSUE THREAD

**Issue by wuhuaxu** [mp911de/lettuce#438]
CDI specification 1.0, 1.1, 1.2..  all says "a bean which can be proxied must has a non-private constructor with no parameters".
But in lettuce 4.3.0.Final, RedisClusterClient dose not have one! It's default constructor is private. RedisClient is still ok!

**Comment by mp911de** [comment]
Thanks for the bug report. That's fixed now.

Please keep in mind that

> a bean which can be proxied must has a non-private constructor with no parameters

(3.15. Unproxyable bean types, https://docs.jboss.org/cdi/spec/1.2/cdi-spec-1.2.pdf)

only applies to `@NormalScope` scopes such as `@ApplicationScoped`, `@RequestScoped` and so on. Other scopes like `@Dependent` and `@Singleton` do not impose these requirements.
So for now it's a good idea to keep `RedisClusterClient` in  @Singleton` scope.
