### ISSUE TITLE
Latency Collector in 5.0.0 Beta1

### ISSUE THREAD

**Issue by GrigorievNick** [mp911de/lettuce#447]
Right now in 5 version Beta1  there is no some lib for metric collection. 
```
DefaultCommandLatencyCollector.isAvailable() == false
```
What dependency i need add, to turn on it?

**Comment by mp911de** [comment]
Checkout https://github.com/mp911de/lettuce/wiki/Dependency-Compatibility-Matrix and the method's JavaDoc:

```
    /**
     * Returns {@literal true} if HdrUtils and LatencyUtils are available on the class path.
     * 
     * @return
     */
    public static boolean isAvailable() {
        return LATENCY_UTILS_AVAILABLE && HDR_UTILS_AVAILABLE;
    }
```

Then add
```
<dependency>
    <groupId>org.latencyutils</groupId>
    <artifactId>LatencyUtils</artifactId>
    <version>2.0.3</version>
</dependency>
```

to your dependencies.

**Comment by GrigorievNick** [comment]
thanks. actually i do not see this in doc, may be it will be goot to add it to this page https://github.com/mp911de/lettuce/wiki/Configuring-Client-resources or to this https://github.com/mp911de/lettuce/wiki/Command-Latency-Metrics
