### ISSUE TITLE
Cannot get lettuce from SBT

### ISSUE THREAD

**Issue by Erwyn** [mp911de/lettuce#449]
Hello, I don't know if this belongs here, or if it is a maven repository related issue. But I'm trying to get lettuce through sbt  by adding this line: `"biz.paluch.redis" % "lettuce" % "4.3.0.Final"`

And all I can get is this:

```
[info] Resolving biz.paluch.redis#lettuce;4.3.0.Final ...
[error] Server access Error: java.security.ProviderException: java.lang.NegativeArraySizeException url=https://repo1.maven.org/maven2/biz/paluch/redis/lettuce/4.3.0.Final/lettuce-4.3.0.Final.pom
```

Please close it if it does not belong here.

**Comment by mp911de** [comment]
Thanks for the ticket. Looks like a version incompatibility issue between your JDK and scala/SBT. Artifacts are available in Maven central (https://repo1.maven.org/maven2/biz/paluch/redis/lettuce/4.3.0.Final/) so closing this one.

**Comment by Erwyn** [comment]
Okay, thanks. You were right openjdk vs oracle ... :(
