### ISSUE TITLE
Commands have Output fields that are nullable and mutable.

### ISSUE THREAD

**Issue by taer** [mp911de/lettuce#45]
Commands can be created with null outputs. I think this could be cleaned up to require non-null Outputs. I think we should also remove the setOutput() call on command as well. Output is used in the RedisStateMachine, and changing output midstream or having a missing one can lead to issues.

From an initial look, only 2 commands have no output. The debugOOM and debugSegfault. Both these kill the server, so there is no output to report. I wasn't able to find any other places where a null output is used.

If this seems OK, I'd like to go down this path. 

Also, is this the best way to discuss code proposals like this?

**Comment by mp911de** [comment]
Hi @taer, 
this is a good starting point for improvement. I actually like the style of communication, face2face isn't always possible and there is no mailing list. So Github as communication platform is great.

You're right, currently only the debug commands have null outputs for not waiting on any response after firing the command. Guess, this can be improved. `ClusterCommand` does no magic when it comes to the outputs.

**Comment by taer** [comment]
@mp911de What are your thoughts about adding jsr305?
```
<dependency>
    <groupId>com.google.code.findbugs</groupId>
    <artifactId>jsr305</artifactId>
    <version>3.0.0</version>
</dependency>
```
It would be a compile time dep, since I'd annotate methods with the Nonnull annotation, which means non-shaded downstream users would now need this.

Intellij helps analyze nulls if we can implement this.

**Comment by mp911de** [comment]
I'd rather go for Sonar in the first place. If you like, we could include it as `<optional>true</optional>`

**Comment by taer** [comment]
I actually just noticed that guava depends on JSR305 already. And I just learned that annotations don't need to be present on the runtime classpath [SO link](https://stackoverflow.com/questions/3567413/why-doesnt-a-missing-annotation-cause-a-classnotfoundexception-at-runtime)

So an optional one won't affect users. Either way I'm planning to limit the annotation to a few initial methods. 

I do like the idea of getting Sonar in place if it's an easy integration

**Comment by mp911de** [comment]
Go for it. Thanks for caring.

**Comment by mp911de** [comment]
lettuce is available on Nemo SonarQube http://nemo.sonarqube.org/dashboard/index/biz.paluch.redis:lettuce

**Comment by mp911de** [comment]
Added jsr305 lib directly in order to omit javadoc failures

**Comment by mp911de** [comment]
Closed for now, no progress and no demand
