### ISSUE TITLE
Null pointer exception at com.lambdaworks.redis.StatefulRedisConnectionImpl.dispatch

### ISSUE THREAD

**Issue by jpen51** [mp911de/lettuce#450]
I am using Lettuce version 4.3.0.Final.  I am creating my redis connection using the ConnectToElastiCacheMaster example.  I am using the asyncronous api. I am running a throughput test and when put under any significant amount of throughput I get a null pointer exception.

```
java.lang.NullPointerException: null
        at com.lambdaworks.redis.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:202)
        at com.lambdaworks.redis.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:1959)
        at com.lambdaworks.redis.AbstractRedisAsyncCommands.hgetall(AbstractRedisAsyncCommands.java:443)
```

**Comment by mp911de** [comment]
Hi @jpen51, 

this looks like a thread sharing issue. You use transactions and share one connection amongst multiple threads. The mentioned line (StatefulRedisConnectionImpl.java:202) adds a command for transaction (`MULTI`) output processing but the transaction is closed by a different thread so you run into a NPE. Please use either a different connection, assign dedicated connections to threads that deal with transactions or use connection-pooling.

**Comment by jpen51** [comment]
Thanks for responding.  What would you recommend I use for this?  What connection would work better? or would pooling be a better option?

**Comment by mp911de** [comment]
It really depends on your use. I'm not a fan of connection pooling because pooling leads to a connection per thread (in the long term) and an increased resource usage. If you can assign dedicated connections to workers that use transactions, then this would be the way to go while keeping a general connection for operations not using transactions (if applicable).

**Comment by jpen51** [comment]
I ended up using a thread for each connection and that worked fine.  Thanks for your help.
