### ISSUE TITLE
Problems with Azure Redis Cluster and lettuce versions 4.2.2 and 4.3.0

### ISSUE THREAD

**Issue by oskyz** [mp911de/lettuce#451]
Hello,

We have an Apache Storm project that uses lettuce to access an Azure Redis Cluster. We were using the lettuce version 4.2.2.Final, and when we tried to scale up the cluster we started receiving these exceptions:

`com.lambdaworks.redis.RedisException: java.lang.IllegalArgumentException: Connection to XXX.XX.XXX.XXX:15000 not allowed. This connection point is not known in the cluster viewjava.lang.IllegalArgumentException: Connection to XXX.XX.XXX.XXX:15000 not allowed. This connection point is not known in the cluster viewConnection to XXX.XX.XXX.XXX:15000 not allowed. This connection point is not known in the cluster view
`
Once we restarted the Storm topology, this exception disappeared. 

Researching a bit, we saw that there was a newer version, the 4.3.0.Final that had these new properties

> This release fixes several issues, provides a streamlined Sorted Sets API and introduces new features for network partition recovery, zero-downtime Redis Cluster reconfiguration and improved resource handling.

So we decided to try that version out. Unfortunately, as soon as we updated our code with this version of lettuce and deployed it into an environment with a Redis cluster, it started to return the same exception (without us modifying the Redis cluster like in the previous time or anything else in the code)

Any ideas what could be the problem?

Thanks,
Javier

**Comment by mp911de** [comment]
Your issue is because of `validateClusterNodeMembership` and a behavior in Lettuce 4.2.2 and earlier.  Disable `validateClusterNodeMembership` in `ClusterClientOptions`.

Some background:

You connect using one endpoint that randomly points to an active Cluster node. Lettuce 4.2.2 and earlier replaced the URI of the node with the given (configured) endpoint and considered that address as cluster node address. Since the cluster answers with its internal host name and port (which is different), the membership validation fails. Check out https://github.com/mp911de/lettuce/wiki/Client-options for details, see also #312.

Lettuce 4.3 should have that issue solved but I will investigate on that issue.

**Comment by oskyz** [comment]
Thanks for your prompt reply. We are implementing that with the version 4.2.2 right now, and will keep you update it with the results.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by oskyz** [comment]
Hi,

We haven't experienced any other problem, so yes please, close this ticket.

Thanks a lot for your help!
Javier

**Comment by akrnjoshi** [comment]
I saw the same issue for version 4.4.1.Final.

**Comment by mp911de** [comment]
Lettuce approaches Redis Cluster rather conservative to prevent connections to unknown nodes. Known nodes are derived from the topology. You can safely disable `validateClusterNodeMembership`, IIRC Lettuce is the only Redis client providing this safeguard.

**Comment by msassak** [comment]
FWIW I am seeing this with `5.0.2.RELEASE` connecting to Redis Cluster hosted on AWS ElastiCache. Disabling `validateClusterNodeMembership` appears to have fixed the problem.

**Comment by chaimcode** [comment]
> Your issue is because of `validateClusterNodeMembership` and a behavior in Lettuce 4.2.2 and earlier. Disable `validateClusterNodeMembership` in `ClusterClientOptions`.
> 
> Some background:
> 
> You connect using one endpoint that randomly points to an active Cluster node. Lettuce 4.2.2 and earlier replaced the URI of the node with the given (configured) endpoint and considered that address as cluster node address. Since the cluster answers with its internal host name and port (which is different), the membership validation fails. Check out https://github.com/mp911de/lettuce/wiki/Client-options for details, see also #312.
> 
> Lettuce 4.3 should have that issue solved but I will investigate on that issue.

thank you.
It's very useful for me
