### ISSUE TITLE
Propose SLAVE_PREFERRED strategy

### ISSUE THREAD

**Issue by Spikhalskiy** [mp911de/lettuce#452]
Hi,

Strategy MASTER_PREFERRED is nearly useless for redis-cluster because slave becomes a master in case of slave fail. (But not in the case if node is unavailable for client only for sure).

On the same time, SLAVE_PREFERRED could be a very useful safe strategy, so it reads from a slave, but if master only is alive for a slot - it switches to master.
For now, we have the only SLAVE strategy for read-from-slave, which is dangerous (If master is alive, but no slaves available - we will continuously try to connect to slave)

WDYT about providing SLAVE_PREFERRED strategy as a safe read from slave implementation for redis-cluster?

**Comment by mp911de** [comment]
Adding a new `ReadFrom.SLAVE_PREFERRED` setting makes sense. `MASTER_PREFERRED` is designed for the failover period during which there might be no master. `ReadFrom` is not limited to Redis Cluster but also used with Master/Slave. `ReadFrom` is an open class, so you can implement custom behavior by extending from `ReadFrom`.

**Comment by mp911de** [comment]
That's implemented now.

**Comment by Spikhalskiy** [comment]
Very cool! Thanks a lot, @mp911de
