### ISSUE TITLE
Avoid or reduce connection attempts to nodes in fail state

### ISSUE THREAD

**Issue by Spikhalskiy** [mp911de/lettuce#453]
Hi,

Lettuce 4.3.0.Final
We have redis-cluster with 3 nodes. Each node has 10 processes. Processes on ports 9000..9004 are master, 9005..9009 are slaves. So, we have 15 masters and 15 slaves.

Lettuce was configured to use ReadFromSlave read implementation. I figured out that it's dangerous option and it leads to proposal https://github.com/mp911de/lettuce/issues/452

Additionally, lettuce configured to use pretty small request timeout (5ms) and large connection timeout (like 1s). 

We lost one node of the cluster. ReadFromSlave forces reads from slaves, which are not available.
It leads to exceptions provided in the [gist](https://gist.github.com/Spikhalskiy/e6d7ff193a717f71658e2fdbb5db1890). In PartitionsException.txt file there you can find full partitions state.

Problem:
A lot of threads stuck trying to setup connection in block manner to nodes which 
- already have a fail state from Redis logs and lettuce aware of it
- we constantly get ConnectTimeoutException trying to connect to it

So, lettuce continues to allow many of incoming threads calling ```get()``` try to establish a connection to a dead node with the big connection timeout in block manner.
This led to server dead in our case.

Proposal:
If lettuce sees that node has ```fail``` state from Redis cluster + node is actually unavailable from prev attempts - don't allow a lot of threads to establish new connections and block on it. Quickly throw "RedisException: Cannot determine a partition to read" in nearly all such cases. For example, allow only one thread at a time to establish a connection to a node which is dead currently.
For now, I see about one quick ```RedisException: connection timed out``` for one long blocking ```ConnectTimeoutException```.

WDYT?

**Comment by mp911de** [comment]
Thanks for your ticket. I think there are various approaches which are valid for their individual use. 

First of all, you can use `ReadFrom.NEAREST` to read from any qualified node without making a distinction, whether the node is a slave or a master.

There are two things which play into your case: The first one is, how lettuce initializes cluster node connections: Cluster connections are obtained lazily which means the first thread requesting a connection pay the penalty for the connection. In your case, it sounds there was no connection established before so your application requests (threads) get blocked with establishing a connection. Connection creation is synchronized so every thread gets blocked after the previous Thread already failed to connect.

The second aspect is: If lettuce established previously a connection and the connection is down, then (depending on disconnected behavior), commands get queued. They time out after a while if the connection remains disconnected.

Datastax' Apache Cassandra driver features the behavior you mentioned. Host connections are managed in the background and the application gets a fast response if no connection is available. This makes it quite hard to debug and see what's going on but applications clearly benefit from not being blocked.

I think, connection creation requires some effort and maybe even command dispatching should be reconsidered to remove the blocking bits.

In the meantime, you can do two things:

1. Initialize all connections upon application start to warm the connection "cache"
2. Hook into `Partitions` retrieval and post-process `Partitions` via `RedisClusterClient.determinePartitions(…)`. You could remove any nodes found invalid yourself which then leads to `RedisException: Cannot determine a partition for slot ...`. Regular topology updates will bring the healthy node back once it's available and your application self-heals then.

**Comment by Spikhalskiy** [comment]
Hi, thanks for your detailed response!

> Initialize all connections upon application start to warm the connection "cache"

This will not help in case of "connection timed out" node. This could only speedup initial requests after app start if nodes are actually working fine, right? This is good, but my main point in this issue and in general now - protect an app from dying in case of a combination of the three factors - long request timeouts + dead node which lettuce is trying to query + huge QPS.

> First of all, you can use ReadFrom.NEAREST to read from any qualified node without making a distinction, whether the node is a slave or a master.

Yeah, for now, I switched to Master Preferred strategy because even Slave Preferred would not help I think - we will try to call this slave first. The problem would be if the whole cluster will dead - looks like we will get the same trouble.

> Hook into Partitions retrieval and post-process Partitions via RedisClusterClient.determinePartitions(…). You could remove any nodes found invalid yourself

Yes, looks like I will do this, for now, to definitely protect from the issue of "connection timeout" node. Looks like I would need to do it with some regularity to clean up after rediscoveries. But, will hack it in some way.

> Cluster connections are obtained lazily which means the first thread requesting a connection pay the penalty for the connection. In your case, it sounds there was no connection established before so your application requests (threads) get blocked with establishing a connection. Connection creation is synchronized so every thread gets blocked after the previous Thread already failed to connect.

By synchronized you don't mean that all connections will try to make a connection one by one and we apply connection timeout period only for thread's own connection attempt, right?
So, we have 1000 threads, all of them trying to call a bad node with connection timeout and we have connection timeout configured for 5 seconds - it doesn't work in a way that the last thread will wait 5000 seconds in this situation, right? It will back in 5 seconds, not more?

**Comment by mp911de** [comment]
> By synchronized you don't mean that all connections will try to make a connection one by one and we apply connection timeout period only for thread's own connection attempt, right?
So, we have 1000 threads, all of them trying to call a bad node with connection timeout and we have connection timeout configured for 5 seconds - it doesn't work in a way that the last thread will wait 5000 seconds in this situation, right? It will back in 5 seconds, not more?

`PooledClusterConnectionProvider` uses internally a `ConcurrentHashMap` to obtain a connection via `computeIfAbsent`. It depends to which hosts connections are attempted. In the worst case, the last thread will wait 5000 seconds.

I was considering using something like LMAX Disruptor in front of `ClusterDistributionChannelWriter`. This way, commands get dispatched to a ring-buffer that is guarded with a maximal queue size (buffer size) and whose processing is decoupled from the command-invoking Thread. This would give you two properties:

1. A global queue size managed through one property (right now the queue size is approximately the configured `queue size` x `number of node connections` x `2` (read and write intents).
2. Threads issuing a command (even for a future) return immediately (without blocking).
3. The additional cost for space and time should be reasonable, I think lettuce has other areas with a larger potential for improvement 😬 

Right now, there's no way to inject a disruptor from outside the package.

**Comment by Spikhalskiy** [comment]
Uh, so if we have 100ms connect timeout, 10 QPS for a dead node will actually block all threads that trying to call this node....

I don't think disruptor is required here in some way... Disruptor is good when we actually do useful work in a Disruptor consumer thread, not just block on io operation... it would be wasting of one more thread. You want to use disruptor to get serialization semantic I think, but it could be done.

Give me some time, I will maybe prepare some very raw version of what could be done...

**Comment by Spikhalskiy** [comment]
Hey, please take a look: https://github.com/Spikhalskiy/lettuce/commit/4c63ad69a8a34396b05c4d56335633f69d5b161d
Code is just awful, but I think it explains my view for solution at least for the worst case.

Absolutely unrelated to this discussion, mentioned this code in ```PooledClusterConnectionProvider```:
```
    @Override
    public void close() {

        this.connections.clear();
        resetFastConnectionCache();

        new HashMap<>(this.connections) //
                .values() //
                .stream() //
                .filter(StatefulConnection::isOpen).forEach(StatefulConnection::close);
    }
```

Is it fine? I think should be something like:
```
    @Override
    public void close() {
        Map<ConnectionKey, StatefulRedisConnection<K, V>> originalConnections = new HashMap<>(this.connections);
        this.connections.clear();
        resetFastConnectionCache();

         //originalConnections
                .values() //
                .stream() //
                .filter(StatefulConnection::isOpen).forEach(StatefulConnection::close);
    }
```

**Comment by mp911de** [comment]
🙈 Good catch. I created #460.

**Comment by mp911de** [comment]
Good catch, I created #460 for the mentioned bug. Thanks @Spikhalskiy for digging into the issue. 

I think there are many approaches that would work. I like the approach to synchronize with `CompletableFuture` because it follows non-blocking connection initialization. I see two things here:

1. I don't like the blocking how it's today. Neither the fact that one client is blocked during connecting nor that many threads are blocked.
2. I don't like that multiple requests are serialized so the last thread pays a penalty with the most waiting time.

These are different problems but still related. For now, I'd like to solve your issue to reduce multiple connection attempts to the same `ConnectionKey` to at most one.

I think the change isn't huge:

1. `ClusterNodeConnectionFactory` would return a `CompletableFuture<StatefulRedisConnection<K, V>>` so connection happens asynchronously. 2.`ConcurrentHashMap` synchronizes on `ConnectionKey` to guarantee only one connection attempt
3. `getOrCreateConnection()` returns early with a future that is used to synchronize
4. If the connection success: 🎉 🎊 
5. If the connection fails, then it's required to the failed `ConnectionKey` **exactly once** from the map and propagate the connection exception.
6. Subsequent attempts start at the point as there would have been no connection, so basically go to 1.

The `ConcurrentHashMap` should be encapsulated with an own type to make the underlying concept more clear.

Does this make sense?

**Comment by Spikhalskiy** [comment]
Yeap, all of this makes perfect sense. Only one potential uncovered problem that I see would be between 4 and 5. So, it's unclear when to remove failed future from the map. So, I think, it should be something like... first thread put a future to map. All other concurrent threads read this future. First thread when gets a result for the future - it removes the future from the map to make it possible for next threads to try to establish new connections.

All of this would guarantee that all threads would spend not much than connection timeout in this code. Further improvements could address initial proposal and don't make additional attempts during some time after connection failing + in a case of the 'fail' node state. But it's the second priority.

**Comment by mp911de** [comment]
Removing the failed future must happen after completion exactly once. I think it's a synchronization issue. Ok, then we've found a viable solution. 

Let's keep the quiet time after connection failure separate. That's something which can be built on top of `RedisClusterClient` that requires slight adjustments to the visibility of `connectStateful` and `connectStatefulAsync` methods. This way you can keep track of failed connections per host and cache the resulting future. `ClusterNodeConnectionFactory.getOrCreateConnection(…)` is per `ConnectionKey` which also incorporates the connection intent (read/write) but in your case you want to group connections by host/port.

**Comment by Spikhalskiy** [comment]
Yes, all solutions looks good in terms of the minimal fix of the largest problem, but the last suggestion would be more easy to extend and flexible.

**Comment by mp911de** [comment]
Cluster node connection progress sharing is now on `master` (`4.4.0-SNAPSHOT`) and `5.x`. Care to give it a try?

**Comment by Spikhalskiy** [comment]
Yeah, definitely interesting to give it a try, because it's a big potential production threat for us. I will make an internal release, rollout this fix into prod and replicate the problem. I will make all of this during the next visit and will reply here.

Just to be sure - we change potential blocking time from unlimited to a connection timeout? So, if node would be down with a connection timeout - all threads will wait for a connection timeout period?
No fast pass back if some thread is trying to establish a connection already and we know that we have been failing for a long time or just previous attempt? I mean Cassandra's like thing or some other more complex handling.

**Comment by mp911de** [comment]
lettuce has a dedicated connection timeout setting in [SocketOptions](http://redis.paluch.biz/docs/api/releases/latest-4.x/com/lambdaworks/redis/SocketOptions.html) since 4.3 that is applied when connecting to a socket. If a connection is in progress, then threads that want to use the same connection, synchronize on the same `ConnectionFuture` instead of sequential connection attempts.

Thanks for the hint about documentation, I'll update it. The Datastax Cassandra driver has a client view whether nodes are up or down. I don't like the approach because there's little to do about it from a client perspective, you can't really opt out and the driver considers a host down for various reasons.

**Comment by Spikhalskiy** [comment]
Tested, we are fine now in a case of failed node. Thank you for your help with this issue!
