### ISSUE TITLE
Unknown channel option warnings in log using UDS

### ISSUE THREAD

**Issue by magdkudama** [mp911de/lettuce#476]
Hello,

* Version: 4.3.0.Final
* Java version: 8 (1.8.0_121-b13) - Oracle

When connecting to Redis using Unix Domain Sockets, I get the following warnings:

```
18:15:05.844 [lettuce-eventExecutorLoop-1-1] WARN  io.netty.bootstrap.Bootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x688c6e87]'
18:15:05.845 [lettuce-eventExecutorLoop-1-1] WARN  io.netty.bootstrap.Bootstrap - Unknown channel option 'TCP_NODELAY' for channel '[id: 0x688c6e87]'
```

So Netty is complaining there's some options set in the parent and handler (I'm just guessing to be honest). At least that's what it looks like?

I can have a look at it on Wednesday, just wanted to post it here in case it's a known error, sounds like an easy fix!

Thanks!

**Comment by mp911de** [comment]
I think we can get rid of those warnings by just not setting these options on domain sockets.

**Comment by mp911de** [comment]
That's fixed now.
