### ISSUE TITLE
Why List of ScoredValue instead of a Map for zrevrangeWithScore?

### ISSUE THREAD

**Issue by kalesh13** [mp911de/lettuce#479]
Hi Marc,

Only today I noticed that zrevrangeWithScore returned a List of ScoredValue. I have to operate on these keys and values. At present I am using a Map to put all the ScoredValue entries and operating on this map. It seems to be unnecessary waste of memory in my scenario.

List.get(index) wont help in getting the field or value while a Map.get(field) should be fine for operating on these sets. I think a Map with key and score should be perfect.

Is there any specific reason to use ScoredValue? Is there any specific usage scenario where having a List of ScoredValue is better than a Map with zrevrangeWithScore command?

Regards
Kalesh

**Comment by mp911de** [comment]
Hi @kalesh13,

Thanks for your question that I find very interesting. Sorted Sets, specifically query methods returning score and value tuples, facilitate various use cases. There are cases in which you require a linear scan over the result and other cases that work better with a `Map`-like lookup for values.

`ScoredValue` is a value type in the Lettuce type hierarchy that abstracts a score along its value. In lettuce 5, the next major version, these types are extended to monad use supporting value/score mapping, `Optional`/`Stream` creation.

Why do you think using `Map<T, Double>` is more memory efficient?

From what I know, I'd argue `List<ScoredValue>` consumes less memory. The value is a reference type, the score a primitive `double`. The `ArrayList` is backed by an `Object` array.

Turning the response to a `Map<T, Double>` requires the score to use a box type which is an object again – this is on par with `ScoredValue`, so no memory efficiency here – and the `Map`, `LinkedHashMap` that is to retain order, using `Map.Entry` elements to store key, value along the hash value, the `next` entry and ` before, after` pointers. It boils down to three additional references and one additional long field.

Does this make sense?

Cheers, 
Mark

**Comment by kalesh13** [comment]
Thanks for the reply Mark.

I mentioned memory efficiency based on my specific usage scenario, where I have to lookup the values and scores. Iterator, looping, storing the same list into a map and all these things results in more time and more memory. What you said is absolutely right, List is better than Map.

Regards,
Kalesh

**Comment by mp911de** [comment]
Agree. May I close this ticket or is there anything else I can assist you with?

**Comment by kalesh13** [comment]
Yeah, sure. Thanks for the support.

**Comment by mp911de** [comment]
One last thing came to my mind (sorry for not mentioning it earlier). You can build the map yourself instead of receiving an already assembled list by using result streaming:

[`zrevrangeWithScores(ScoredValueStreamingChannel<V>, K, long, long)`](http://redis.paluch.biz/docs/api/releases/latest/com/lambdaworks/redis/api/sync/RedisSortedSetCommands.html#zrevrangeWithScores-com.lambdaworks.redis.output.ScoredValueStreamingChannel-K-long-long-)

`ScoredValueStreamingChannel` is a callback interface that gets called for each `ScoredValue`. You can build a `Map` yourself and do not pay the cost for creating an additional list.
