### ISSUE TITLE
Latency metrics is reset even if set to false

### ISSUE THREAD

**Issue by ameenhere** [mp911de/lettuce#487]
I have used lettuce client to connect to a local redis cache. I have enabled latency metrics collector after adding the required LatencyUtils dependencies. I have also disabled resetLatenciesAfterEvent() by setting it to false in the CommandLatencyCollectorOptions.  However I see that the latencies are reset no matter what config I set resetLatenciesAfterEvent() to. 

My Environment
-Java 8 (1.8.0_111)
-Lettuce version - 3.5.0.Final

Here is what I did
Created a spring boot application (version 1.4.2.RELEASE).
Though my local env has Java 8, I need it to be compatible with Java 7 as well hence using Java 7 supported version of lettuce. Configured the clientResources for lettuce redis client as follows

```java
DefaultClientResources.Builder builder = new DefaultClientResources.Builder();
builder = builder.commandLatencyCollectorOptions( new DefaultCommandLatencyCollectorOptions.Builder().resetLatenciesAfterEvent(false).targetUnit(TimeUnit.MILLISECONDS).build()).commandLatencyPublisherOptions(new DefaultEventPublisherOptions.Builder().eventEmitInterval(10, TimeUnit.SECONDS).build());
            

            Func1<Event, Boolean> function = new Func1<Event, Boolean>() {

                @Override
                public Boolean call(Event t) {
                    return (t instanceof CommandLatencyEvent);
                }
            };
            Action1<? super CommandLatencyEvent> onNext = new Action1<CommandLatencyEvent>() {

                @Override
                public void call(CommandLatencyEvent t) {
                    LOGGER.info("Redis Latency Metrics = {}" ,t.getLatencies());

                }
            };
clientResources = builder.build(); clientResources.eventBus().get().filter(function).cast(CommandLatencyEvent.class).subscribe(onNext);
```

I have an endpoint which does 10 operations of get,set,del each. I hit the endpoint once, the first log comes as follows 

```
Redis Latency Metrics = {[local:any -> localhost/127.0.0.1:6379, commandType=AUTH]=[count=1, timeUnit=MILLISECONDS, firstResponse=[min=9, max=9, percentiles={50.0=9, 90.0=9, 95.0=9, 99.0=9, 99.9=9}], completion=[min=14, max=14, percentiles={50.0=14, 90.0=14, 95.0=14, 99.0=14, 99.9=14}]], [local:any -> localhost/127.0.0.1:6379, commandType=DEL]=[count=10, timeUnit=MILLISECONDS, firstResponse=[min=0, max=0, percentiles={50.0=0, 90.0=0, 95.0=0, 99.0=0, 99.9=0}], completion=[min=0, max=1, percentiles={50.0=0, 90.0=0, 95.0=1, 99.0=1, 99.9=1}]], [local:any -> localhost/127.0.0.1:6379, commandType=GET]=[count=10, timeUnit=MILLISECONDS, firstResponse=[min=0, max=0, percentiles={50.0=0, 90.0=0, 95.0=0, 99.0=0, 99.9=0}], completion=[min=0, max=0, percentiles={50.0=0, 90.0=0, 95.0=0, 99.0=0, 99.9=0}]], [local:any -> localhost/127.0.0.1:6379, commandType=SET]=[count=10, timeUnit=MILLISECONDS, firstResponse=[min=0, max=0, percentiles={50.0=0, 90.0=0, 95.0=0, 99.0=0, 99.9=0}], completion=[min=0, max=1, percentiles={50.0=0, 90.0=0, 95.0=1, 99.0=1, 99.9=1}]]}
```

which is expected and is correct with a count of 10 for those commands. If I wait for the next event without performing any other commands I get the following empty metrics log

```
Redis Latency Metrics = {}
```
Now I hit my endpoint, which does the same 10 operations of get,set,del each again. And the subsequent event logs this

```
Redis Latency Metrics = {[local:any -> localhost/127.0.0.1:6379, commandType=DEL]=[count=10, timeUnit=MILLISECONDS, firstResponse=[min=0, max=0, percentiles={50.0=0, 90.0=0, 95.0=0, 99.0=0, 99.9=0}], completion=[min=0, max=6, percentiles={50.0=1, 90.0=3, 95.0=6, 99.0=6, 99.9=6}]], [local:any -> localhost/127.0.0.1:6379, commandType=GET]=[count=10, timeUnit=MILLISECONDS, firstResponse=[min=0, max=2, percentiles={50.0=0, 90.0=0, 95.0=2, 99.0=2, 99.9=2}], completion=[min=0, max=4, percentiles={50.0=1, 90.0=1, 95.0=4, 99.0=4, 99.9=4}]], [local:any -> localhost/127.0.0.1:6379, commandType=SET]=[count=10, timeUnit=MILLISECONDS, firstResponse=[min=0, max=0, percentiles={50.0=0, 90.0=0, 95.0=0, 99.0=0, 99.9=0}], completion=[min=1, max=2, percentiles={50.0=1, 90.0=2, 95.0=2, 99.0=2, 99.9=2}]]}
```

Now it shows count 10 again, but since I have disabled reset, it should have been 20. Am I missing something?

**Comment by mp911de** [comment]
You're doing everything right, that's a bug.

**Comment by mp911de** [comment]
Please note that Lettuce 3.5 is out of maintenance, the next version to use is 4.2 with Spring Boot 1.5/Spring Data Redis 1.8.

**Comment by ameenhere** [comment]
In fact my core application is on Java 7, and its not a spring boot application either. 4.x is only Java 8 compatible. Any way this could be fixed in the Java 7 supported versions as well?

**Comment by mp911de** [comment]
I back-ported the change to the 3.x branch so you can build the library yourself. Don't expect another 3.x release – there have been too many bug fixed in the 4.x line so publishing another 3.x release would ship with all the existing bugs. Backporting the fixes (about 50 issues) isn't something that I can do on my own right now.
