### ISSUE TITLE
Move to Netty 4.1.9.Final

### ISSUE THREAD

**Issue by odiszapc** [mp911de/lettuce#488]
You are using 4.1.6 now. How about to move to the latest one? Thanks!

**Comment by mp911de** [comment]
Do you want to submit a PR?

**Comment by odiszapc** [comment]
Sure

**Comment by odiszapc** [comment]
PR: https://github.com/mp911de/lettuce/pull/489

**Comment by mp911de** [comment]
Closed via d80a364b9cc57c36caf7285dc78f7d98640b3319.
