### ISSUE TITLE
firstResponseLatency depends on command completion time

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#491]
`firstResponseLatency` depends on command completion time, not the sent time. The longer command completion takes, the higher first response latency is. 

It should depend on sent time because first response happens only once on the first completion and should not depend on command completion

`CommandHandler.recordLatency`:

```
 long firstResponseLatency = nanoTime() - withLatency.getFirstResponse();
```

**Comment by shankyty** [comment]
Thanks for quick fix, which version on maven repo will have this fix?

**Comment by mp911de** [comment]
```xml
<repositories>
  <repository>
    <id>sonatype-nexus-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```
Use version 4.3.2-SNAPSHOT.
