### ISSUE TITLE
Provide an option to connect to Redis via Unix Domain Sockets

### ISSUE THREAD

**Issue by taer** [mp911de/lettuce#52]
Having an option to connect to a local Redis via UDS would be nice to have. It's allegedly faster.
From: http://redis.io/topics/benchmarks
> Depending on the platform, unix domain sockets can achieve around 50% more throughput than the TCP/IP loopback (on Linux for instance)

Netty supports UDS in 4.0.26 
https://twitter.com/normanmaurer/status/573090616000843777

Additional info from chat
>mostly adding a new schemes to RedisURI, say redis-socket and redis-sentinel-socket or something like that then upgrading to latest netty, adding the socket resolution and maybe some bootstrap options.

**Comment by mp911de** [comment]
@taer I created a first draft of unix domain sockets. It works currently only on linux x86_64 since netty has only that support builtin. I guess, you could compile the native parts as needed.

**Comment by mp911de** [comment]
Merged into master.
