### ISSUE TITLE
Pipelining for certain cluster commands

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#66]
Handle transparent pipelining of following multikey commands:

* `del`
* `mget`
* `mset`
* `msetnx`

**Comment by vleushin** [comment]
Where can I see code and tests for this functionality? Is it on github?

**Comment by mp911de** [comment]
Look here: a2bc2de7a7150f7b6c7f2006d2477ecc9cd2e8e5
and: https://github.com/mp911de/lettuce/blob/multi-key-pipelining/src/test/java/com/lambdaworks/redis/cluster/AdvancedClusterClientTest.java

**Comment by mp911de** [comment]
Need to add support for `mget ` with streaming

**Comment by mp911de** [comment]
Implemented.
