### ISSUE TITLE
ERR MULTI calls can not be nested

### ISSUE THREAD

**Issue by carlvine500** [mp911de/lettuce#67]
my code:
public static void main(String[] args) throws Exception {
		final RedisConnection<String, byte[]> sync = new RedisClient("10.58.52.60", 5021)
				.connect(new BytesCodec());
		 sync.flushall();
		 
		 
		 final CountDownLatch c = new CountDownLatch(1);
			new Thread(new Runnable() {
				public void run() {
					try {
						c.await();
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					sync.multi();
					sync.set("a", Thread.currentThread().getName().getBytes());
					sync.set("a1", Thread.currentThread().getName().getBytes());
					System.out.println(1234);
				}
			}).start();
			new Thread(new Runnable() {
				public void run() {
					try {
						c.await();
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
					sync.multi();
					sync.set("a", Thread.currentThread().getName().getBytes());
					sync.set("a1", Thread.currentThread().getName().getBytes());
					sync.exec();
					System.out.println(5678);
				}
			}).start();
		
			c.countDown();
			
			
	}

output:
Exception in thread "Thread-2" com.lambdaworks.redis.RedisCommandExecutionException: ERR MULTI calls can not be nested
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:76)
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:59)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at $Proxy5.multi(Unknown Source)
	at com.lambdaworks.redis.AsyncConnectionConcurrentTest$2.run(AsyncConnectionConcurrentTest.java:44)
	at java.lang.Thread.run(Thread.java:662)
1234

**Comment by mp911de** [comment]
Thank you for your report. lettuce connections are in general threadsafe but not stateless. Issuing a `MULTI` command will turn lettuce connections into a transactional state. All commands issued after a `MULTI` command are then within the transaction scope until either `EXEC` or `DISCARD` are issued.

The connection state means also, that calling `MULTI` twice will initiate the transaction twice and then try again to start the transaction. The mentioned exception `ERR MULTI calls can not be nested` is issued by Redis. I assume, that your test case can change the connection in a state, where the first transaction state might be lost, but I have to check this first.

Can you tell me about your expectation in this case?

**Comment by carlvine500** [comment]
diffrent business data stored in redis with diffrent dbIndex ,  
I will concurrently send command ( multi ; select x; set y ; exec;)
then I get this error.

**Comment by mp911de** [comment]
You will need two connections, every connection can be at one database at a time. All commands are issued immediately to Redis, even those preceded by a `MULTI` commands. This means commands are not buffered until you fire `EXEC`.

**Comment by carlvine500** [comment]
thanks , I will try it .

**Comment by mp911de** [comment]
Until now, no further action, but it might be worth having a sketch for a transactional buffer utility.

**Comment by benjamin-bader** [comment]
@mp911de Apologies for resurrecting such an old thread, but I'm having a little conceptual trouble with this. I just hit this error, and don't quite understand something you said upthread:

> lettuce connections are in general threadsafe but not stateless

What does this mean?  Generally, statefulness implies non-threadsafe.  Is it the case that a MULTI call requires thread synchronization?  That is, if we use MULTI, must we guarantee that only that thread is actively using the connection?

**Comment by mp911de** [comment]
Statefulness and thread-safety are not mutually exclusive. Lettuce connections are initialized and handed over to the application. The initial state is (looking at transactions), that the connection is not in a transactional state. This state can be changed concurrently but requires external synchronization. Without synchronization, things like interleaving or other race conditions may happen.

> That is, if we use MULTI, must we guarantee that only that thread is actively using the connection?

In short: Yes, only a single thread is allowed to actively use the connection. 

The longer version is:

Without changing the state, a single connection is thread-safe and can be shared across multiple threads. If you need to change the state (run transactions), then you need to introduce some sort of isolation. That can be synchronization (thread 1 runs its transaction and awaits its completion, then thread 2 runs its transaction and so on) or allocating connections per thread (invocation) by e.g. using connection pooling.

**Comment by benjamin-bader** [comment]
Thanks for the sensible explanation.  I see now what you mean by "threadsafe but stateful".  Individual commands are sent in a threadsafe manner, but application logic (transactions) must be synchronized at a higher level.
