### ISSUE TITLE
Reactive support

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#68]
Add another layer between command creation and execution (today a command is created and immediately executed). Reactive commands should be only executed (example from RxJava as soon as `call` is invoked). 

This layer could be located between the command builder and the async connection itself.

**Comment by mp911de** [comment]
4.x package: `com.lambdaworks.redis.api.rx`

New interfaces:

* BaseRedisRxConnection
* RedisHashesRxConnection
* RedisHLLRxConnection
* RedisKeysRxConnection
* RedisListsRxConnection
* RedisScriptingRxConnection
* RedisSentinelRxConnection
* RedisServerRxConnection
* RedisSetsRxConnection
* RedisSortedSetsRxConnection
* RedisStringsRxConnection
* RedisTransactionalRxConnection

**Comment by mp911de** [comment]
Open issues:

## Collection results
What about collection result types like lists and sets? Should these be dissolved into particular elements?

Example:
```java
// sync API
List<String> result = redis.hkeys("...");
```

```java
// either
Observable<String> result = redis.hkeys("...");

// or
Observable<List<String>> result = redis.hkeys("...");
```

## PubSub
Provide **hot** observables for subscription listeners?

## Cluster
Provide observable commands also for node-selection commands? (Commands executed on multiple cluster nodes)

**Comment by xasx** [comment]
What would be the advantage of emitting `List<String>` (Iterable!) over simply `String`?

Grouping could be done using `groupBy` operator.

**Comment by mp911de** [comment]
None. 

Rx does not differentiate between one and many elements. Dissolving `Iterable`s and other multi-element containers such as `Map` into singular values or tuples fit very well into the Rx pattern. This is, however, a change of result types in contrast to other API's within lettuce. 

If you approach from pure Rx dissolved elements are welcome, but if you're used to `List`s and `Map`s then you have to shift from collections to reactions on elements.

**Comment by mp911de** [comment]
Btw. nice to hear from you @xasx

**Comment by mp911de** [comment]
Javadocs available at http://redis.paluch.biz/docs/api/snapshots/latest/com/lambdaworks/redis/api/rx/RedisReactiveCommands.html

**Comment by mp911de** [comment]
Observables emit single elements and `Map`s
