### ISSUE TITLE
Improve codecs

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#70]
* Provide byte[] codec
* Use dedicated String codec when creating connections without a codec

**Comment by carlvine500** [comment]
performance will be better , codec will be done by user-thread  insteadof netty-thread.

**Comment by mp911de** [comment]
It's a bit different. Performance depends on how the codec works internally. 

If you work with one connection only (does not matter whether single- or multi-threaded), you won't notice a difference. The String encoding is non-blocking, the String decoding is blocking. But even this has very little effect, since Redis works mostly single-threaded. You'll get benefits if you connect to multiple Redis instances. Multiple connections won't share a codec and won't block each other.

The change is from share the String codec amongst the whole client to share the String codec amongst a logical connection. A logical connection is either a sync/async connection to Redis Standalone/Sentinel or a connection to a whole cluster. The cluster connection consists of multiple connections behind the scenes. So here the String codec is shared again among multiple physical Redis instances.
