### ISSUE TITLE
Support NX|XX|CH|INCR options in ZADD

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#74]
ZADD options (Redis 3.0.2 or greater)
ZADD supports a list of options, specified after the name of the key and before the first score argument. Options are:
* XX: Only update elements that already exist. Never add elements.
* NX: Don't update already existing elements. Always add new elements.
* CH: Modify the return value from the number of new elements added, to the total number of elements changed (CH is an abbreviation of changed). Changed elements are new elements added and elements already existing for which the score was updated. So elements specified in the command line having the same score as they had in the past are not counted. Note: normally the return value of ZADD only counts the number of new elements added.
* INCR: When this option is specified ZADD acts like ZINCRBY. Only one score-element pair can be specified in this mode.

**Comment by Kevin0010** [comment]
@mp911de dose Spring Data Redis support this?
I can only find two method about zadd in SDR:
```
	Boolean add(K key, V value, double score);
	Long add(K key, Set<TypedTuple<V>> tuples);
```
but it seem that the only two method didn't provide NX|XX|CH|INCR options.
Thank you.

**Comment by lijian0706** [comment]
I have the same question
