### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by carlvine500** [mp911de/lettuce#88]
https://github.com/mp911de/lettuce.git
version: 589
jdk: 1.6 

mvn package 
......
[ERROR] /D:/lettuce.mp911de/temp/trunk/src/main/java/com/lambdaworks/redis/AbstractRedisClient.java:[96,37] D:\lettuce.mp911de\temp\trunk\src\main\java\com\lambdaworks\redis\AbstractRedisClient.java:96: not supported type java.lang.Object,java.lang.Object,java.lang.Object not support variable type's restriction K,V,T  
[ERROR] find： <K,V,T>T
[ERROR] need： java.lang.Object
......

**Comment by mp911de** [comment]
You need at least Java 8 to compile (altough the compile level is set back to 1.6).
