### ISSUE TITLE
lettuce cluster performance is non-linear ?

### ISSUE THREAD

**Issue by carlvine500** [mp911de/lettuce#89]
my pc : 4core i7 8G
single redis one node , concurrent 200 ,total task 1000*1000, with ByteArrayCodec, QPS=45852
redis cluster four node, concurrent 200 ,total task 1000*1000, with ByteArrayCodec, QPS=30758
why cluster's performance is not so good as single redis?

**Comment by mp911de** [comment]
Which commands did you use and which version? Can you post your test code?

You should not use more threads than you've got cores, since context switching will consume performance. Some 4 threads for 4 cores should be ok.
Connections to particular cluster nodes are opened on demand and impact your benchmark. You should make sure, that all connections are opened before you start measuring time.

**Comment by carlvine500** [comment]
single redis test
----------------------
	public static void main(String[] args) throws Exception {
		final RedisConnection<String, byte[]> sync1 = new RedisClient("10.126.53.98", 7000).connect(new BytesCodec());
// concurrent=200 ,total task 100*10000
		StressTestUtils.testAndPrint(200, 100 * 10000, new StressTask() {

			@Override
			public Object doTask() throws Exception {
				byte[] bs = sync1.get("b");
				return null;
			}
		});
	}
cluster test
----------------------
	public static void main(String[] args) throws InterruptedException {
		RedisClusterClient clusterClient = new RedisClusterClient(ImmutableList.of(RedisURI.Builder.redis("10.126.53.98", 7000).build()));
		final RedisClusterConnection< byte[], byte[]> connection = clusterClient.connectCluster(new ByteArrayCodec());
		String string = connection.clusterNodes();
		System.out.println(string);
		final AtomicLong i = new AtomicLong();
		final byte[] a = "a".getBytes();
		connection.get("a".getBytes());
// concurrent=200 ,total task 100*10000
		StressTestUtils.testAndPrint(200, 100*10000, new StressTask() {
			@Override
			public Object doTask() throws Exception {
				byte[] bytes = (""+i.incrementAndGet()).getBytes();
				connection.get(bytes);
				// async.
				// System.out.println(set.get());
				return null;
			}
		});
		
	}

**Comment by mp911de** [comment]
There are 3 reasons, why standalone is faster than cluster in the test you've measured:

1. The lookup of partitions within `com.lambdaworks.redis.cluster.models.partitions.Partitions` is in 3.0 unoptimized. Version 4.0 carries a better lookup (see comparison below)
2. The connection management and cluster determination carries a certain level of complexity. That code is not optimized and has some potential allow speed-up.
3. There is no warming in your test

In general, you should provide a percentile (95th) or a list of benchmark numbers. I executed the code below multiple times, and you can see the variance in the results.

Here are the results of the optimized vs. unoptimized partition lookup:
```
Clustered:
w/o Partition optimization
Duration: 1925 ms (1,93 sec), operations: 250000, 129870,13 ops/sec 
Duration: 1608 ms (1,61 sec), operations: 250000, 155472,64 ops/sec 
Duration: 2267 ms (2,27 sec), operations: 250000, 110277,90 ops/sec 
Duration: 1328 ms (1,33 sec), operations: 250000, 188253,01 ops/sec 
Duration: 2111 ms (2,11 sec), operations: 250000, 118427,29 ops/sec 
Duration: 1789 ms (1,79 sec), operations: 250000, 139742,87 ops/sec 
Duration: 1460 ms (1,46 sec), operations: 250000, 171232,88 ops/sec 
Duration: 1184 ms (1,18 sec), operations: 250000, 211148,65 ops/sec 
Duration: 2992 ms (2,99 sec), operations: 250000, 83556,15 ops/sec 

with Partition optimization
Duration: 1571 ms (1,57 sec), operations: 250000, 159134,31 ops/sec 
Duration: 1507 ms (1,51 sec), operations: 250000, 165892,50 ops/sec 
Duration: 921 ms (0,92 sec), operations: 250000, 271444,08 ops/sec 
Duration: 1238 ms (1,24 sec), operations: 250000, 201938,61 ops/sec 
Duration: 1114 ms (1,11 sec), operations: 250000, 224416,52 ops/sec 
Duration: 1503 ms (1,50 sec), operations: 250000, 166334,00 ops/sec 
Duration: 1302 ms (1,30 sec), operations: 250000, 192012,29 ops/sec 
Duration: 829 ms (0,83 sec), operations: 250000, 301568,15 ops/sec 
Duration: 1586 ms (1,59 sec), operations: 250000, 157629,26 ops/sec 
Duration: 1241 ms (1,24 sec), operations: 250000, 201450,44 ops/sec 
```

HTH, Mark

**Comment by carlvine500** [comment]
nice ! 
I find   slotCache[] in Partitions.java now .

**Comment by mp911de** [comment]
I would like to keep this ticket open.  I want to back port the improvement and improve internal connection management. There is about 30% of potential speed up.

**Comment by mp911de** [comment]
I pushed a new branch (https://github.com/mp911de/lettuce/tree/improved-cluster-performance), you can give the code a try if you want. I noticed, that the Redis instances consume more CPU and the Java process itself less.
