### ISSUE TITLE
Pipelining for lettuce (or: flush after `n` commands)

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#92]
Redis commands are rather small (usually below 50 bytes). Every write is written by `writeAndFlush`. A single connection operated with one thread can achieve currently between 100K ops/sec to 150K ops/sec.

The `flush` part within netty is currently the costly and limiting part. Tests with batching (writing multiple commands in async/observable mode without flush after every write) and an explicit `flush` every 20 to 50 commands pushed throughput to 470K ops/sec to 800K ops/sec.

Goal of this ticket is to implement a batching mode that allows buffering of commands and an explicit write (or even auto-flush every `n` commands).

**Comment by mp911de** [comment]
Performance test results:

```
Warming:
Duration: 415 ms (0,42 sec), operations: 50000, 120481,93 ops/sec 
Duration: 143 ms (0,14 sec), operations: 50000, 349650,35 ops/sec 

Measure:
Duration: 101 ms (0,10 sec), operations: 50000, 495049,50 ops/sec 
Duration: 117 ms (0,12 sec), operations: 50000, 427350,43 ops/sec 
Duration: 125 ms (0,13 sec), operations: 50000, 400000,00 ops/sec 
Duration: 134 ms (0,13 sec), operations: 50000, 373134,33 ops/sec 
Duration: 106 ms (0,11 sec), operations: 50000, 471698,11 ops/sec 
Duration: 103 ms (0,10 sec), operations: 50000, 485436,89 ops/sec 
Duration: 98 ms (0,10 sec), operations: 50000, 510204,08 ops/sec 
Duration: 86 ms (0,09 sec), operations: 50000, 581395,35 ops/sec 
Duration: 99 ms (0,10 sec), operations: 50000, 505050,51 ops/sec 
Duration: 62 ms (0,06 sec), operations: 50000, 806451,61 ops/sec
Mean: 505577,08 ops/sec 
```

**Comment by itamarhaber** [comment]
That's **very** nice :+1:

**Comment by mp911de** [comment]
Todo:
* Merge in 4.0
* Docs

**Comment by mp911de** [comment]
Documentation: https://github.com/mp911de/lettuce/wiki/Pipelining-and-command-flushing

**Comment by mp911de** [comment]
Added throughput improvements
